//go:build !noasm && arm64
// Code generated by VecGo. DO NOT EDIT.

TEXT ·_vdot_neon(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	MOVD ret+24(FP), R3
	WORD $0xa9bf7bfd    // stp	x29, x30, [sp,
	WORD $0x91001c48    // add	x8, x2,
	WORD $0xf100005f    // cmp	x2,
	WORD $0x9a82b108    // csel	x8, x8, x2, lt
	WORD $0x910003fd    // mov	x29, sp
	WORD $0x927df10a    // and	x10, x8,
	WORD $0x9343fd09    // asr	x9, x8,
	WORD $0xcb0a0048    // sub	x8, x2, x10
	WORD $0x7100053f    // cmp	w9,
	WORD $0x5400032b    // b.lt	.LBB0_5
	WORD $0xb27d7fea    // mov	x10,
	WORD $0xaa0103ec    // mov	x12, x1
	WORD $0x8b090d4a    // add	x10, x10, x9, lsl
	WORD $0x927d7d4a    // and	x10, x10,
	WORD $0x9100214a    // add	x10, x10,
	WORD $0x6f00e401    // movi	v1.2d,
	WORD $0x6f00e400    // movi	v0.2d,
	WORD $0x8b0a080b    // add	x11, x0, x10, lsl

LBB0_2:
	WORD $0xacc10c02 // ldp	q2, q3, [x0],
	WORD $0x71000529 // subs	w9, w9,
	WORD $0xacc11584 // ldp	q4, q5, [x12],
	WORD $0x4e22cc81 // fmla	v1.4s, v4.4s, v2.4s
	WORD $0x4e23cca0 // fmla	v0.4s, v5.4s, v3.4s
	WORD $0x54ffff61 // b.ne	.LBB0_2
	WORD $0x8b0a0821 // add	x1, x1, x10, lsl
	WORD $0xaa0b03e0 // mov	x0, x11
	WORD $0x7100051f // cmp	w8,
	WORD $0x5400016a // b.ge	.LBB0_6

LBB0_4:
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	WORD $0xd65f03c0 // ret

LBB0_5:
	WORD $0x6f00e400 // movi	v0.2d,
	WORD $0x6f00e401 // movi	v1.2d,
	WORD $0x7100051f // cmp	w8,
	WORD $0x54fffeeb // b.lt	.LBB0_4

LBB0_6:
	WORD $0x92407d08 // and	x8, x8,

LBB0_7:
	WORD $0x4ea11c22 // mov	v2.16b, v1.16b
	WORD $0xf1000508 // subs	x8, x8,
	WORD $0xbc404403 // ldr	s3, [x0],
	WORD $0xbc404424 // ldr	s4, [x1],
	WORD $0x1f040863 // fmadd	s3, s3, s4, s2
	WORD $0x6e040461 // mov	v1.s[0], v3.s[0]
	WORD $0x54ffff41 // b.ne	.LBB0_7
	WORD $0x6e040462 // mov	v2.s[0], v3.s[0]
	WORD $0x4ea21c41 // mov	v1.16b, v2.16b
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0x6e20d400 // faddp	v0.4s, v0.4s, v0.4s
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	WORD $0xd65f03c0 // ret

TEXT ·_squared_l2_neon(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	MOVD result+24(FP), R3
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp,
	WORD $0x91000c48       // add	x8, x2,
	WORD $0xf100005f       // cmp	x2,
	WORD $0x9a82b108       // csel	x8, x8, x2, lt
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x9342fd09       // asr	x9, x8,
	WORD $0x7100053f       // cmp	w9,
	WORD $0x4b090848       // sub	w8, w2, w9, lsl
	WORD $0x5400028b       // b.lt	.LBB1_5
	WORD $0x6f00e400       // movi	v0.2d,
	WORD $0x92407d2a       // and	x10, x9,
	WORD $0xaa0003eb       // mov	x11, x0
	WORD $0xaa0103ec       // mov	x12, x1

LBB1_2:
	WORD $0x3cc10561 // ldr	q1, [x11],
	WORD $0x3cc10582 // ldr	q2, [x12],
	WORD $0xf100054a // subs	x10, x10,
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x6e21dc21 // fmul	v1.4s, v1.4s, v1.4s
	WORD $0x4e21d400 // fadd	v0.4s, v0.4s, v1.4s
	WORD $0x54ffff41 // b.ne	.LBB1_2
	WORD $0x7100011f // cmp	w8,
	WORD $0x5400014c // b.gt	.LBB1_6

LBB1_4:
	WORD $0x6e004001 // ext	v1.16b, v0.16b, v0.16b,
	WORD $0x0e21d400 // fadd	v0.2s, v0.2s, v1.2s
	WORD $0x2e20d400 // faddp	v0.2s, v0.2s, v0.2s
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	WORD $0xd65f03c0 // ret

LBB1_5:
	WORD $0x6f00e400 // movi	v0.2d,
	WORD $0x7100011f // cmp	w8,
	WORD $0x54ffff0d // b.le	.LBB1_4

LBB1_6:
	WORD $0x531e7529 // lsl	w9, w9,
	WORD $0x7100051f // cmp	w8,
	WORD $0x937e7d29 // sbfiz	x9, x9,
	WORD $0x3ce96801 // ldr	q1, [x0, x9]
	WORD $0x3ce96822 // ldr	q2, [x1, x9]
	WORD $0x4ea2d421 // fsub	v1.4s, v1.4s, v2.4s
	WORD $0x6e21dc21 // fmul	v1.4s, v1.4s, v1.4s
	WORD $0x4e21d401 // fadd	v1.4s, v0.4s, v1.4s
	WORD $0x6e040420 // mov	v0.s[0], v1.s[0]
	WORD $0x54fffdc0 // b.eq	.LBB1_4
	WORD $0x6e0c2420 // mov	v0.s[1], v1.s[1]
	WORD $0x71000d1f // cmp	w8,
	WORD $0x54fffd63 // b.lo	.LBB1_4
	WORD $0x6e144420 // mov	v0.s[2], v1.s[2]
	WORD $0x6e004001 // ext	v1.16b, v0.16b, v0.16b,
	WORD $0x0e21d400 // fadd	v0.2s, v0.2s, v1.2s
	WORD $0x2e20d400 // faddp	v0.2s, v0.2s, v0.2s
	WORD $0xbd000060 // str	s0, [x3]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp],
	WORD $0xd65f03c0 // ret
