version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - unconvert
    - goconst
    - gocritic
    - prealloc
    - predeclared
    - nolintlint
    - whitespace
    - errorlint
    - durationcheck
    - nilerr
    - revive
    - bodyclose
    - wastedassign
    - makezero
    - thelper
    # Performance-critical additions
    - copyloopvar   # loop variable captures → hidden heap allocations
    - nilnil        # ambiguous (nil, nil) → downstream alloc/checks
    # Note: forcetypeassert disabled - all hits are sync.Pool patterns where
    # type is guaranteed. Adding ok checks would add branches in hot paths.

  # Disabled for high-performance database code:
  # - dupl: Intentional code duplication for hot-path inlining
  # - gocyclo: Complex functions are acceptable in database internals
  # - nakedret: Not a concern for experienced Go developers
  # - nestif: Deeply nested conditions are sometimes necessary
  # - unparam: Parameters kept for interface compatibility or future use

  settings:
    goconst:
      min-len: 3
      min-occurrences: 4

    gocritic:
      enabled-checks:
        - boolExprSimplify
        - builtinShadow
        - emptyFallthrough
        - hexLiteral
        - initClause
        - nilValReturn
        - rangeValCopy
        - stringXbytes
        - unnecessaryBlock
        - weakCond
      disabled-checks:
        - ifElseChain        # if-else can be clearer than switch in hot paths
        - elseif             # stylistic preference
        - typeSwitchVar      # stylistic preference
        - dupBranchBody      # sometimes intentional for clarity

    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-naming
        - name: increment-decrement
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code

    gosec:
      excludes:
        - G103  # unsafe.Pointer is necessary for SIMD and memory-mapped code
        - G104  # Errors ignored intentionally in performance-critical paths (reviewed individually)
        - G115  # Integer overflow conversions are intentional and validated
        - G301  # Directory permissions 0755 acceptable for database directories
        - G304  # File path variables are safe within the codebase
        - G404  # Weak random is fine for non-crypto
        - G602  # Slice bounds are manually validated in hot paths

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  exclusions:
    rules:
      - path: _test\.go$
        linters:
          - errcheck
          - gosec
          - goconst
          - gocritic
          - predeclared
          - prealloc
          - unused
          - staticcheck
          - revive
          - wastedassign
          - makezero

      - path: examples/
        linters:
          - errcheck
          - gosec
          - goconst
          - unused
          - gocritic
          - predeclared
          - revive
          - ineffassign
          - staticcheck
          - wastedassign

      - path: benchmark_test/
        linters:
          - errcheck
          - gosec
          - goconst
          - gocritic
          - predeclared
          - wastedassign

      - path: integration_test/
        linters:
          - errcheck
          - gosec
          - goconst
          - gocritic
          - predeclared
          - wastedassign
          - unused

      # SVE2 stubs are platform-specific and may appear unused on non-ARM
      - path: internal/simd/.*_sve2_stubs\.go$
        linters:
          - unused

      # Allow Close() errors to be ignored in defer statements
      - linters:
          - errcheck
        text: "Error return value of .*.Close.*is not checked"

      # Allow Flush() errors to be ignored
      - linters:
          - errcheck
        text: "Error return value of .*.Flush.*is not checked"

      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)"'

      - linters:
          - revive
        text: "parameter '.*' seems to be unused"

      # Staticcheck quick-fix suggestions (stylistic, not bugs)
      - linters:
          - staticcheck
        text: "QF1003"  # "could use tagged switch" - if-else is often clearer
      - linters:
          - staticcheck
        text: "QF1008"  # "could remove embedded field from selector"
      - linters:
          - staticcheck
        text: "S1034"   # type switch assignment suggestion
      - linters:
          - staticcheck
        text: "SA6002"  # sync.Pool allocation hint - we manage pool correctly

      # nilnil: (nil, nil) is intentional for "all matches" / "no filter" semantics
      - linters:
          - nilnil
        text: "return both a .nil. error"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: false