// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·dotBatchAvx512(SB), NOSPLIT, $0-40
	MOVQ query+0(FP), DI
	MOVQ targets+8(FP), SI
	MOVQ dim+16(FP), DX
	MOVQ n+24(FP), CX
	MOVQ out+32(FP), R8

	BYTE $0x55 // pushq	%rbp
	WORD $0x5741 // pushq	%r15
	WORD $0x5641 // pushq	%r14
	WORD $0x5541 // pushq	%r13
	WORD $0x5441 // pushq	%r12
	BYTE $0x53 // pushq	%rbx
	LONG $0x28ec8348 // subq	$0x28, %rsp
	LONG $0x24348948 // movq	%rsi, (%rsp)
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JLE LBB1_54
	LONG $0xf0428d48 // leaq	-0x10(%rdx), %rax
	LONG $0x40fa8348 // cmpq	$0x40, %rdx
	JGE LBB1_2
	LONG $0x10fa8348 // cmpq	$0x10, %rdx
	JGE LBB1_17
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JLE LBB1_23
	WORD $0xd089 // movl	%edx, %eax
	WORD $0xe083; BYTE $0x03 // andl	$0x3, %eax
	QUAD $0xfffffffffffcb949; WORD $0x7fff // movabsq	$0x7ffffffffffffffc, %r9 # imm = 0x7FFFFFFFFFFFFFFC
	WORD $0x2149; BYTE $0xd1 // andq	%rdx, %r9
	LONG $0x241c8b48 // movq	(%rsp), %rbx
	LONG $0x0c538d4c // leaq	0xc(%rbx), %r10
	QUAD $0x00000000951c8d4c // leaq	(,%rdx,4), %r11
	WORD $0x3145; BYTE $0xf6 // xorl	%r14d, %r14d
	JMP LBB1_26
LBB1_33:
	LONG $0x117a81c4; WORD $0xb004 // vmovss	%xmm0, (%r8,%r14,4)
	WORD $0x014d; BYTE $0xda // addq	%r11, %r10
	WORD $0x014c; BYTE $0xdb // addq	%r11, %rbx
	WORD $0x894d; BYTE $0xfe // movq	%r15, %r14
	WORD $0x3949; BYTE $0xcf // cmpq	%rcx, %r15
	JE LBB1_54
LBB1_26:
	LONG $0x017e8d4d // leaq	0x1(%r14), %r15
	WORD $0x3949; BYTE $0xcf // cmpq	%rcx, %r15
	JGE LBB1_28
	WORD $0x894c; BYTE $0xfe // movq	%r15, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x24248b4c // movq	(%rsp), %r12
	LONG $0x0c180f41; BYTE $0xb4 // prefetcht0	(%r12,%rsi,4)
LBB1_28:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0xf631 // xorl	%esi, %esi
	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JCS LBB1_30
LBB1_29:
	LONG $0x0c10fac5; BYTE $0xb7 // vmovss	(%rdi,%rsi,4), %xmm1
	LONG $0x5410fac5; WORD $0x04b7 // vmovss	0x4(%rdi,%rsi,4), %xmm2
	LONG $0x9979c2c4; WORD $0xb24c; BYTE $0xf4 // vfmadd132ss	-0xc(%r10,%rsi,4), %xmm0, %xmm1 # xmm1 = (xmm1 * mem) + xmm0
	LONG $0xb969c2c4; WORD $0xb24c; BYTE $0xf8 // vfmadd231ss	-0x8(%r10,%rsi,4), %xmm2, %xmm1 # xmm1 = (xmm2 * mem) + xmm1
	LONG $0x5410fac5; WORD $0x08b7 // vmovss	0x8(%rdi,%rsi,4), %xmm2
	LONG $0x9971c2c4; WORD $0xb254; BYTE $0xfc // vfmadd132ss	-0x4(%r10,%rsi,4), %xmm1, %xmm2 # xmm2 = (xmm2 * mem) + xmm1
	LONG $0x4410fac5; WORD $0x0cb7 // vmovss	0xc(%rdi,%rsi,4), %xmm0
	LONG $0x9969c2c4; WORD $0xb204 // vfmadd132ss	(%r10,%rsi,4), %xmm2, %xmm0 # xmm0 = (xmm0 * mem) + xmm2
	LONG $0x04c68348 // addq	$0x4, %rsi
	WORD $0x3949; BYTE $0xf1 // cmpq	%rsi, %r9
	JNE LBB1_29
LBB1_30:
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JE LBB1_33
	LONG $0xb3248d4c // leaq	(%rbx,%rsi,4), %r12
	LONG $0xb7348d48 // leaq	(%rdi,%rsi,4), %rsi
	WORD $0x3145; BYTE $0xed // xorl	%r13d, %r13d
LBB1_32:
	LONG $0x107aa1c4; WORD $0xae0c // vmovss	(%rsi,%r13,4), %xmm1
	LONG $0xb97182c4; WORD $0xac04 // vfmadd231ss	(%r12,%r13,4), %xmm1, %xmm0 # xmm0 = (xmm1 * mem) + xmm0
	WORD $0xff49; BYTE $0xc5 // incq	%r13
	WORD $0x394c; BYTE $0xe8 // cmpq	%r13, %rax
	JNE LBB1_32
	JMP LBB1_33
LBB1_2:
	LONG $0xc04a8d4c // leaq	-0x40(%rdx), %r9
	QUAD $0x0000000095148d4c // leaq	(,%rdx,4), %r10
	LONG $0x241c8b48 // movq	(%rsp), %rbx
	LONG $0x009b8d4c; WORD $0x0001; BYTE $0x00 // leaq	0x100(%rbx), %r11
	WORD $0x3145; BYTE $0xf6 // xorl	%r14d, %r14d
	JMP LBB1_3
LBB1_15:
	LONG $0x117a81c4; WORD $0xb804 // vmovss	%xmm0, (%r8,%r15,4)
	WORD $0x014c; BYTE $0xd3 // addq	%r10, %rbx
	WORD $0x014d; BYTE $0xd3 // addq	%r10, %r11
	WORD $0x3949; BYTE $0xce // cmpq	%rcx, %r14
	JE LBB1_54
LBB1_3:
	WORD $0x894d; BYTE $0xf7 // movq	%r14, %r15
	WORD $0xff49; BYTE $0xc6 // incq	%r14
	WORD $0x3949; BYTE $0xce // cmpq	%rcx, %r14
	JGE LBB1_5
	WORD $0x894c; BYTE $0xf6 // movq	%r14, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x24248b4c // movq	(%rsp), %r12
	LONG $0x0c180f41; BYTE $0xb4 // prefetcht0	(%r12,%rsi,4)
LBB1_5:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0x894d; BYTE $0xdd // movq	%r11, %r13
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xd257e8c5 // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	WORD $0x3145; BYTE $0xe4 // xorl	%r12d, %r12d
LBB1_6:
	QUAD $0x000200a38c180f42; BYTE $0x00 // prefetcht0	0x200(%rbx,%r12,4)
	LONG $0x487cb162; WORD $0x2410; BYTE $0xa7 // vmovups	(%rdi,%r12,4), %zmm4
	QUAD $0x01a76c10487cb162 // vmovups	0x40(%rdi,%r12,4), %zmm5
	QUAD $0x02a77410487cb162 // vmovups	0x80(%rdi,%r12,4), %zmm6
	QUAD $0x03a77c10487cb162 // vmovups	0xc0(%rdi,%r12,4), %zmm7
	LONG $0x485db262; WORD $0x04b8; BYTE $0xa3 // vfmadd231ps	(%rbx,%r12,4), %zmm4, %zmm0 # zmm0 = (zmm4 * mem) + zmm0
	QUAD $0x01a34cb84855b262 // vfmadd231ps	0x40(%rbx,%r12,4), %zmm5, %zmm1 # zmm1 = (zmm5 * mem) + zmm1
	QUAD $0x02a354b8484db262 // vfmadd231ps	0x80(%rbx,%r12,4), %zmm6, %zmm2 # zmm2 = (zmm6 * mem) + zmm2
	QUAD $0x03a35cb84845b262 // vfmadd231ps	0xc0(%rbx,%r12,4), %zmm7, %zmm3 # zmm3 = (zmm7 * mem) + zmm3
	WORD $0x894c; BYTE $0xee // movq	%r13, %rsi
	LONG $0x40c48349 // addq	$0x40, %r12
	LONG $0x00c58149; WORD $0x0001; BYTE $0x00 // addq	$0x100, %r13            # imm = 0x100
	WORD $0x394d; BYTE $0xcc // cmpq	%r9, %r12
	JLE LBB1_6
	LONG $0x4874f162; WORD $0xc058 // vaddps	%zmm0, %zmm1, %zmm0
	LONG $0x4864f162; WORD $0xca58 // vaddps	%zmm2, %zmm3, %zmm1
	LONG $0x4874f162; WORD $0xc058 // vaddps	%zmm0, %zmm1, %zmm0
	WORD $0x3949; BYTE $0xc4 // cmpq	%rax, %r12
	JGT LBB1_10
LBB1_8:
	LONG $0x487cb162; WORD $0x0c10; BYTE $0xa7 // vmovups	(%rdi,%r12,4), %zmm1
	LONG $0x4875f262; WORD $0x06b8 // vfmadd231ps	(%rsi), %zmm1, %zmm0 # zmm0 = (zmm1 * mem) + zmm0
	LONG $0x10c48349 // addq	$0x10, %r12
	LONG $0x40c68348 // addq	$0x40, %rsi
	WORD $0x3949; BYTE $0xc4 // cmpq	%rax, %r12
	JLE LBB1_8
LBB1_10:
	LONG $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$0x1, %zmm0, %ymm1
	LONG $0x487cf162; WORD $0xc158 // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc8c6f9c5; BYTE $0x01 // vshufpd	$0x1, %xmm0, %xmm0, %xmm1 # xmm1 = xmm0[1,0]
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc816fac5 // vmovshdup	%xmm0, %xmm1    # xmm1 = xmm0[1,1,3,3]
	LONG $0xc158fac5 // vaddss	%xmm1, %xmm0, %xmm0
	WORD $0x894c; BYTE $0xe6 // movq	%r12, %rsi
	WORD $0x2948; BYTE $0xd6 // subq	%rdx, %rsi
	JGE LBB1_15
	WORD $0x8941; BYTE $0xd5 // movl	%edx, %r13d
	WORD $0x2945; BYTE $0xe5 // subl	%r12d, %r13d
	LONG $0x03e58341 // andl	$0x3, %r13d
	JE LBB1_13
LBB1_12:
	LONG $0x107aa1c4; WORD $0xa70c // vmovss	(%rdi,%r12,4), %xmm1
	LONG $0xb971a2c4; WORD $0xa304 // vfmadd231ss	(%rbx,%r12,4), %xmm1, %xmm0 # xmm0 = (xmm1 * mem) + xmm0
	WORD $0xff49; BYTE $0xc4 // incq	%r12
	WORD $0xff49; BYTE $0xcd // decq	%r13
	JNE LBB1_12
LBB1_13:
	LONG $0xfcfe8348 // cmpq	$-0x4, %rsi
	JHI LBB1_15
LBB1_14:
	LONG $0x107aa1c4; WORD $0xa70c // vmovss	(%rdi,%r12,4), %xmm1
	LONG $0x107aa1c4; WORD $0xa754; BYTE $0x04 // vmovss	0x4(%rdi,%r12,4), %xmm2
	LONG $0x9979a2c4; WORD $0xa30c // vfmadd132ss	(%rbx,%r12,4), %xmm0, %xmm1 # xmm1 = (xmm1 * mem) + xmm0
	LONG $0xb969a2c4; WORD $0xa34c; BYTE $0x04 // vfmadd231ss	0x4(%rbx,%r12,4), %xmm2, %xmm1 # xmm1 = (xmm2 * mem) + xmm1
	LONG $0x107aa1c4; WORD $0xa754; BYTE $0x08 // vmovss	0x8(%rdi,%r12,4), %xmm2
	LONG $0x9971a2c4; WORD $0xa354; BYTE $0x08 // vfmadd132ss	0x8(%rbx,%r12,4), %xmm1, %xmm2 # xmm2 = (xmm2 * mem) + xmm1
	LONG $0x107aa1c4; WORD $0xa744; BYTE $0x0c // vmovss	0xc(%rdi,%r12,4), %xmm0
	LONG $0x9969a2c4; WORD $0xa344; BYTE $0x0c // vfmadd132ss	0xc(%rbx,%r12,4), %xmm2, %xmm0 # xmm0 = (xmm0 * mem) + xmm2
	LONG $0x04c48349 // addq	$0x4, %r12
	WORD $0x394c; BYTE $0xe2 // cmpq	%r12, %rdx
	JNE LBB1_14
	JMP LBB1_15
LBB1_17:
	WORD $0x8949; BYTE $0xc6 // movq	%rax, %r14
	LONG $0xf0e68349 // andq	$-0x10, %r14
	WORD $0x8948; BYTE $0xc6 // movq	%rax, %rsi
	LONG $0x04eec148 // shrq	$0x4, %rsi
	WORD $0xff48; BYTE $0xc6 // incq	%rsi
	WORD $0x8949; BYTE $0xd1 // movq	%rdx, %r9
	WORD $0x294d; BYTE $0xf1 // subq	%r14, %r9
	LONG $0x10c68349 // addq	$0x10, %r14
	LONG $0xefc18349 // addq	$-0x11, %r9
	LONG $0x244c894c; BYTE $0x10 // movq	%r9, 0x10(%rsp)
	WORD $0x8941; BYTE $0xf5 // movl	%esi, %r13d
	LONG $0x03e58341 // andl	$0x3, %r13d
	LONG $0xfce68348 // andq	$-0x4, %rsi
	LONG $0x24748948; BYTE $0x18 // movq	%rsi, 0x18(%rsp)
	WORD $0xd689 // movl	%edx, %esi
	WORD $0xe683; BYTE $0x03 // andl	$0x3, %esi
	LONG $0x24748948; BYTE $0x08 // movq	%rsi, 0x8(%rsp)
	LONG $0x242c8b48 // movq	(%rsp), %rbp
	LONG $0xc0bd8d4c; WORD $0x0000; BYTE $0x00 // leaq	0xc0(%rbp), %r15
	QUAD $0x0000000095248d4c // leaq	(,%rdx,4), %r12
	LONG $0x246c894c; BYTE $0x20 // movq	%r13, 0x20(%rsp)
	LONG $0x06e5c141 // shll	$0x6, %r13d
	WORD $0x3145; BYTE $0xdb // xorl	%r11d, %r11d
	JMP LBB1_18
LBB1_53:
	LONG $0x117a81c4; WORD $0x9004 // vmovss	%xmm0, (%r8,%r10,4)
	WORD $0x014d; BYTE $0xe7 // addq	%r12, %r15
	WORD $0x014c; BYTE $0xe5 // addq	%r12, %rbp
	WORD $0x3949; BYTE $0xcb // cmpq	%rcx, %r11
	JE LBB1_54
LBB1_18:
	WORD $0x894d; BYTE $0xda // movq	%r11, %r10
	WORD $0xff49; BYTE $0xc3 // incq	%r11
	WORD $0x3949; BYTE $0xcb // cmpq	%rcx, %r11
	JGE LBB1_20
	WORD $0x894c; BYTE $0xde // movq	%r11, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x240c8b4c // movq	(%rsp), %r9
	LONG $0x0c180f41; BYTE $0xb1 // prefetcht0	(%r9,%rsi,4)
LBB1_20:
	LONG $0x30f88348 // cmpq	$0x30, %rax
	JCC LBB1_44
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	JMP LBB1_46
LBB1_44:
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0x24748b48; BYTE $0x18 // movq	0x18(%rsp), %rsi
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
LBB1_45:
	LONG $0x487cb162; WORD $0x0410; BYTE $0x8f // vmovups	(%rdi,%r9,4), %zmm0
	QUAD $0x018f5410487cb162 // vmovups	0x40(%rdi,%r9,4), %zmm2
	QUAD $0x028f5c10487cb162 // vmovups	0x80(%rdi,%r9,4), %zmm3
	QUAD $0x038f6410487cb162 // vmovups	0xc0(%rdi,%r9,4), %zmm4
	QUAD $0xfd8f449848759262 // vfmadd132ps	-0xc0(%r15,%r9,4), %zmm1, %zmm0 # zmm0 = (zmm0 * mem) + zmm1
	QUAD $0xfe8f44b8486d9262 // vfmadd231ps	-0x80(%r15,%r9,4), %zmm2, %zmm0 # zmm0 = (zmm2 * mem) + zmm0
	QUAD $0xff8f44b848659262 // vfmadd231ps	-0x40(%r15,%r9,4), %zmm3, %zmm0 # zmm0 = (zmm3 * mem) + zmm0
	LONG $0x485d9262; WORD $0x04b8; BYTE $0x8f // vfmadd231ps	(%r15,%r9,4), %zmm4, %zmm0 # zmm0 = (zmm4 * mem) + zmm0
	LONG $0x40c18349 // addq	$0x40, %r9
	LONG $0x487cf162; WORD $0xc828 // vmovaps	%zmm0, %zmm1
	LONG $0xfcc68348 // addq	$-0x4, %rsi
	JNE LBB1_45
LBB1_46:
	LONG $0x247c8348; WORD $0x0020 // cmpq	$0x0, 0x20(%rsp)
	JE LBB1_49
	QUAD $0x000000008d348d4a // leaq	(,%r9,4), %rsi
	WORD $0x0148; BYTE $0xee // addq	%rbp, %rsi
	LONG $0x8f0c8d4e // leaq	(%rdi,%r9,4), %r9
	WORD $0xdb31 // xorl	%ebx, %ebx
LBB1_48:
	LONG $0x487cd162; WORD $0x0c10; BYTE $0x19 // vmovups	(%r9,%rbx), %zmm1
	LONG $0x4875f262; WORD $0x04b8; BYTE $0x1e // vfmadd231ps	(%rsi,%rbx), %zmm1, %zmm0 # zmm0 = (zmm1 * mem) + zmm0
	LONG $0x40c38348 // addq	$0x40, %rbx
	WORD $0x3949; BYTE $0xdd // cmpq	%rbx, %r13
	JNE LBB1_48
LBB1_49:
	LONG $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$0x1, %zmm0, %ymm1
	LONG $0x487cf162; WORD $0xc158 // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc8c6f9c5; BYTE $0x01 // vshufpd	$0x1, %xmm0, %xmm0, %xmm1 # xmm1 = xmm0[1,0]
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc816fac5 // vmovshdup	%xmm0, %xmm1    # xmm1 = xmm0[1,1,3,3]
	LONG $0xc158fac5 // vaddss	%xmm1, %xmm0, %xmm0
	WORD $0x3949; BYTE $0xd6 // cmpq	%rdx, %r14
	JGE LBB1_53
	LONG $0x24748b48; BYTE $0x08 // movq	0x8(%rsp), %rsi
	WORD $0x894d; BYTE $0xf1 // movq	%r14, %r9
	WORD $0x8548; BYTE $0xf6 // testq	%rsi, %rsi
	JE LBB1_52
LBB1_51:
	LONG $0x107aa1c4; WORD $0x8f0c // vmovss	(%rdi,%r9,4), %xmm1
	LONG $0xb971a2c4; WORD $0x8d44; BYTE $0x00 // vfmadd231ss	(%rbp,%r9,4), %xmm1, %xmm0 # xmm0 = (xmm1 * mem) + xmm0
	WORD $0xff49; BYTE $0xc1 // incq	%r9
	WORD $0xff48; BYTE $0xce // decq	%rsi
	JNE LBB1_51
LBB1_52:
	LONG $0x247c8348; WORD $0x0310 // cmpq	$0x3, 0x10(%rsp)
	JCS LBB1_53
LBB1_55:
	LONG $0x107aa1c4; WORD $0x8f0c // vmovss	(%rdi,%r9,4), %xmm1
	LONG $0x107aa1c4; WORD $0x8f54; BYTE $0x04 // vmovss	0x4(%rdi,%r9,4), %xmm2
	LONG $0x9979a2c4; WORD $0x8d4c; BYTE $0x00 // vfmadd132ss	(%rbp,%r9,4), %xmm0, %xmm1 # xmm1 = (xmm1 * mem) + xmm0
	LONG $0xb969a2c4; WORD $0x8d4c; BYTE $0x04 // vfmadd231ss	0x4(%rbp,%r9,4), %xmm2, %xmm1 # xmm1 = (xmm2 * mem) + xmm1
	LONG $0x107aa1c4; WORD $0x8f54; BYTE $0x08 // vmovss	0x8(%rdi,%r9,4), %xmm2
	LONG $0x9971a2c4; WORD $0x8d54; BYTE $0x08 // vfmadd132ss	0x8(%rbp,%r9,4), %xmm1, %xmm2 # xmm2 = (xmm2 * mem) + xmm1
	LONG $0x107aa1c4; WORD $0x8f44; BYTE $0x0c // vmovss	0xc(%rdi,%r9,4), %xmm0
	LONG $0x9969a2c4; WORD $0x8d44; BYTE $0x0c // vfmadd132ss	0xc(%rbp,%r9,4), %xmm2, %xmm0 # xmm0 = (xmm0 * mem) + xmm2
	LONG $0x04c18349 // addq	$0x4, %r9
	WORD $0x394c; BYTE $0xca // cmpq	%r9, %rdx
	JNE LBB1_55
	JMP LBB1_53
LBB1_23:
	LONG $0x01f98348 // cmpq	$0x1, %rcx
	JNE LBB1_34
	WORD $0xf631 // xorl	%esi, %esi
LBB1_40:
	WORD $0xc1f6; BYTE $0x01 // testb	$0x1, %cl
	JE LBB1_54
	LONG $0x01468d48 // leaq	0x1(%rsi), %rax
	WORD $0x3948; BYTE $0xc8 // cmpq	%rcx, %rax
	JGE LBB1_43
	LONG $0xc2af0f48 // imulq	%rdx, %rax
	LONG $0x240c8b48 // movq	(%rsp), %rcx
	LONG $0x810c180f // prefetcht0	(%rcx,%rax,4)
LBB1_43:
	QUAD $0x00000000b004c741 // movl	$0x0, (%r8,%rsi,4)
LBB1_54:
	LONG $0x28c48348 // addq	$0x28, %rsp
	BYTE $0x5b // popq	%rbx
	WORD $0x5c41 // popq	%r12
	WORD $0x5d41 // popq	%r13
	WORD $0x5e41 // popq	%r14
	WORD $0x5f41 // popq	%r15
	BYTE $0x5d // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET
LBB1_34:
	QUAD $0xfffffffffffcb848; WORD $0x7fff // movabsq	$0x7ffffffffffffffc, %rax # imm = 0x7FFFFFFFFFFFFFFC
	LONG $0x02c88348 // orq	$0x2, %rax
	WORD $0x2148; BYTE $0xc8 // andq	%rcx, %rax
	QUAD $0x00000000953c8d48 // leaq	(,%rdx,4), %rdi
	QUAD $0x00000000d50c8d4c // leaq	(,%rdx,8), %r9
	WORD $0x3145; BYTE $0xdb // xorl	%r11d, %r11d
	LONG $0x24148b4c // movq	(%rsp), %r10
	JMP LBB1_35
LBB1_39:
	QUAD $0x000000049844c743; BYTE $0x00 // movl	$0x0, 0x4(%r8,%r11,4)
	WORD $0x014d; BYTE $0xca // addq	%r9, %r10
	WORD $0x8949; BYTE $0xf3 // movq	%rsi, %r11
	WORD $0x3948; BYTE $0xf0 // cmpq	%rsi, %rax
	JE LBB1_40
LBB1_35:
	LONG $0x01738d49 // leaq	0x1(%r11), %rsi
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JGE LBB1_37
	LONG $0x0c180f41; BYTE $0x3a // prefetcht0	(%r10,%rdi)
LBB1_37:
	QUAD $0x000000009804c743 // movl	$0x0, (%r8,%r11,4)
	LONG $0x02738d49 // leaq	0x2(%r11), %rsi
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JGE LBB1_39
	LONG $0x0c180f43; BYTE $0x0a // prefetcht0	(%r10,%r9)
	JMP LBB1_39

TEXT ·squaredL2BatchAvx512(SB), NOSPLIT, $0-40
	MOVQ query+0(FP), DI
	MOVQ targets+8(FP), SI
	MOVQ dim+16(FP), DX
	MOVQ n+24(FP), CX
	MOVQ out+32(FP), R8

	BYTE $0x55 // pushq	%rbp
	WORD $0x5741 // pushq	%r15
	WORD $0x5641 // pushq	%r14
	WORD $0x5541 // pushq	%r13
	WORD $0x5441 // pushq	%r12
	BYTE $0x53 // pushq	%rbx
	LONG $0x28ec8348 // subq	$0x28, %rsp
	LONG $0x24348948 // movq	%rsi, (%rsp)
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JLE LBB0_54
	LONG $0xf0428d48 // leaq	-0x10(%rdx), %rax
	LONG $0x40fa8348 // cmpq	$0x40, %rdx
	JGE LBB0_2
	LONG $0x10fa8348 // cmpq	$0x10, %rdx
	JGE LBB0_17
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	JLE LBB0_23
	WORD $0xd089 // movl	%edx, %eax
	WORD $0xe083; BYTE $0x03 // andl	$0x3, %eax
	QUAD $0xfffffffffffcb949; WORD $0x7fff // movabsq	$0x7ffffffffffffffc, %r9 # imm = 0x7FFFFFFFFFFFFFFC
	WORD $0x2149; BYTE $0xd1 // andq	%rdx, %r9
	LONG $0x241c8b48 // movq	(%rsp), %rbx
	LONG $0x0c538d4c // leaq	0xc(%rbx), %r10
	QUAD $0x00000000951c8d4c // leaq	(,%rdx,4), %r11
	WORD $0x3145; BYTE $0xf6 // xorl	%r14d, %r14d
	JMP LBB0_26
LBB0_33:
	LONG $0x117a81c4; WORD $0xb004 // vmovss	%xmm0, (%r8,%r14,4)
	WORD $0x014d; BYTE $0xda // addq	%r11, %r10
	WORD $0x014c; BYTE $0xdb // addq	%r11, %rbx
	WORD $0x894d; BYTE $0xfe // movq	%r15, %r14
	WORD $0x3949; BYTE $0xcf // cmpq	%rcx, %r15
	JE LBB0_54
LBB0_26:
	LONG $0x017e8d4d // leaq	0x1(%r14), %r15
	WORD $0x3949; BYTE $0xcf // cmpq	%rcx, %r15
	JGE LBB0_28
	WORD $0x894c; BYTE $0xfe // movq	%r15, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x24248b4c // movq	(%rsp), %r12
	LONG $0x0c180f41; BYTE $0xb4 // prefetcht0	(%r12,%rsi,4)
LBB0_28:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0xf631 // xorl	%esi, %esi
	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JCS LBB0_30
LBB0_29:
	LONG $0x0c10fac5; BYTE $0xb7 // vmovss	(%rdi,%rsi,4), %xmm1
	LONG $0x5410fac5; WORD $0x04b7 // vmovss	0x4(%rdi,%rsi,4), %xmm2
	LONG $0x5c72c1c4; WORD $0xb24c; BYTE $0xf4 // vsubss	-0xc(%r10,%rsi,4), %xmm1, %xmm1
	LONG $0x5c6ac1c4; WORD $0xb254; BYTE $0xf8 // vsubss	-0x8(%r10,%rsi,4), %xmm2, %xmm2
	LONG $0xa971e2c4; BYTE $0xc8 // vfmadd213ss	%xmm0, %xmm1, %xmm1 # xmm1 = (xmm1 * xmm1) + xmm0
	LONG $0x4410fac5; WORD $0x08b7 // vmovss	0x8(%rdi,%rsi,4), %xmm0
	LONG $0x5c7ac1c4; WORD $0xb25c; BYTE $0xfc // vsubss	-0x4(%r10,%rsi,4), %xmm0, %xmm3
	LONG $0xa969e2c4; BYTE $0xd1 // vfmadd213ss	%xmm1, %xmm2, %xmm2 # xmm2 = (xmm2 * xmm2) + xmm1
	LONG $0x4410fac5; WORD $0x0cb7 // vmovss	0xc(%rdi,%rsi,4), %xmm0
	LONG $0x5c7ac1c4; WORD $0xb204 // vsubss	(%r10,%rsi,4), %xmm0, %xmm0
	LONG $0xa961e2c4; BYTE $0xda // vfmadd213ss	%xmm2, %xmm3, %xmm3 # xmm3 = (xmm3 * xmm3) + xmm2
	LONG $0xa979e2c4; BYTE $0xc3 // vfmadd213ss	%xmm3, %xmm0, %xmm0 # xmm0 = (xmm0 * xmm0) + xmm3
	LONG $0x04c68348 // addq	$0x4, %rsi
	WORD $0x3949; BYTE $0xf1 // cmpq	%rsi, %r9
	JNE LBB0_29
LBB0_30:
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JE LBB0_33
	LONG $0xb3248d4c // leaq	(%rbx,%rsi,4), %r12
	LONG $0xb7348d48 // leaq	(%rdi,%rsi,4), %rsi
	WORD $0x3145; BYTE $0xed // xorl	%r13d, %r13d
LBB0_32:
	LONG $0x107aa1c4; WORD $0xae0c // vmovss	(%rsi,%r13,4), %xmm1
	LONG $0x5c7281c4; WORD $0xac0c // vsubss	(%r12,%r13,4), %xmm1, %xmm1
	LONG $0xb971e2c4; BYTE $0xc1 // vfmadd231ss	%xmm1, %xmm1, %xmm0 # xmm0 = (xmm1 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc5 // incq	%r13
	WORD $0x394c; BYTE $0xe8 // cmpq	%r13, %rax
	JNE LBB0_32
	JMP LBB0_33
LBB0_2:
	LONG $0xc04a8d4c // leaq	-0x40(%rdx), %r9
	QUAD $0x0000000095148d4c // leaq	(,%rdx,4), %r10
	LONG $0x241c8b48 // movq	(%rsp), %rbx
	LONG $0x009b8d4c; WORD $0x0001; BYTE $0x00 // leaq	0x100(%rbx), %r11
	WORD $0x3145; BYTE $0xf6 // xorl	%r14d, %r14d
	JMP LBB0_3
LBB0_15:
	LONG $0x117a81c4; WORD $0xb804 // vmovss	%xmm0, (%r8,%r15,4)
	WORD $0x014c; BYTE $0xd3 // addq	%r10, %rbx
	WORD $0x014d; BYTE $0xd3 // addq	%r10, %r11
	WORD $0x3949; BYTE $0xce // cmpq	%rcx, %r14
	JE LBB0_54
LBB0_3:
	WORD $0x894d; BYTE $0xf7 // movq	%r14, %r15
	WORD $0xff49; BYTE $0xc6 // incq	%r14
	WORD $0x3949; BYTE $0xce // cmpq	%rcx, %r14
	JGE LBB0_5
	WORD $0x894c; BYTE $0xf6 // movq	%r14, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x24248b4c // movq	(%rsp), %r12
	LONG $0x0c180f41; BYTE $0xb4 // prefetcht0	(%r12,%rsi,4)
LBB0_5:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	WORD $0x894d; BYTE $0xdd // movq	%r11, %r13
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xd257e8c5 // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	WORD $0x3145; BYTE $0xe4 // xorl	%r12d, %r12d
LBB0_6:
	QUAD $0x000200a38c180f42; BYTE $0x00 // prefetcht0	0x200(%rbx,%r12,4)
	LONG $0x487cb162; WORD $0x2410; BYTE $0xa7 // vmovups	(%rdi,%r12,4), %zmm4
	QUAD $0x01a76c10487cb162 // vmovups	0x40(%rdi,%r12,4), %zmm5
	QUAD $0x02a77410487cb162 // vmovups	0x80(%rdi,%r12,4), %zmm6
	QUAD $0x03a77c10487cb162 // vmovups	0xc0(%rdi,%r12,4), %zmm7
	LONG $0x485cb162; WORD $0x245c; BYTE $0xa3 // vsubps	(%rbx,%r12,4), %zmm4, %zmm4
	QUAD $0x01a36c5c4854b162 // vsubps	0x40(%rbx,%r12,4), %zmm5, %zmm5
	QUAD $0x02a3745c484cb162 // vsubps	0x80(%rbx,%r12,4), %zmm6, %zmm6
	QUAD $0x03a37c5c4844b162 // vsubps	0xc0(%rbx,%r12,4), %zmm7, %zmm7
	WORD $0x894c; BYTE $0xee // movq	%r13, %rsi
	LONG $0x485df262; WORD $0xc4b8 // vfmadd231ps	%zmm4, %zmm4, %zmm0 # zmm0 = (zmm4 * zmm4) + zmm0
	LONG $0x4855f262; WORD $0xcdb8 // vfmadd231ps	%zmm5, %zmm5, %zmm1 # zmm1 = (zmm5 * zmm5) + zmm1
	LONG $0x484df262; WORD $0xd6b8 // vfmadd231ps	%zmm6, %zmm6, %zmm2 # zmm2 = (zmm6 * zmm6) + zmm2
	LONG $0x4845f262; WORD $0xdfb8 // vfmadd231ps	%zmm7, %zmm7, %zmm3 # zmm3 = (zmm7 * zmm7) + zmm3
	LONG $0x40c48349 // addq	$0x40, %r12
	LONG $0x00c58149; WORD $0x0001; BYTE $0x00 // addq	$0x100, %r13            # imm = 0x100
	WORD $0x394d; BYTE $0xcc // cmpq	%r9, %r12
	JLE LBB0_6
	LONG $0x4874f162; WORD $0xc058 // vaddps	%zmm0, %zmm1, %zmm0
	LONG $0x4864f162; WORD $0xca58 // vaddps	%zmm2, %zmm3, %zmm1
	LONG $0x4874f162; WORD $0xc058 // vaddps	%zmm0, %zmm1, %zmm0
	WORD $0x3949; BYTE $0xc4 // cmpq	%rax, %r12
	JGT LBB0_10
LBB0_8:
	LONG $0x487cb162; WORD $0x0c10; BYTE $0xa7 // vmovups	(%rdi,%r12,4), %zmm1
	LONG $0x4874f162; WORD $0x0e5c // vsubps	(%rsi), %zmm1, %zmm1
	LONG $0x4875f262; WORD $0xc1b8 // vfmadd231ps	%zmm1, %zmm1, %zmm0 # zmm0 = (zmm1 * zmm1) + zmm0
	LONG $0x10c48349 // addq	$0x10, %r12
	LONG $0x40c68348 // addq	$0x40, %rsi
	WORD $0x3949; BYTE $0xc4 // cmpq	%rax, %r12
	JLE LBB0_8
LBB0_10:
	LONG $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$0x1, %zmm0, %ymm1
	LONG $0x487cf162; WORD $0xc158 // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc8c6f9c5; BYTE $0x01 // vshufpd	$0x1, %xmm0, %xmm0, %xmm1 # xmm1 = xmm0[1,0]
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc816fac5 // vmovshdup	%xmm0, %xmm1    # xmm1 = xmm0[1,1,3,3]
	LONG $0xc158fac5 // vaddss	%xmm1, %xmm0, %xmm0
	WORD $0x894c; BYTE $0xe6 // movq	%r12, %rsi
	WORD $0x2948; BYTE $0xd6 // subq	%rdx, %rsi
	JGE LBB0_15
	WORD $0x8941; BYTE $0xd5 // movl	%edx, %r13d
	WORD $0x2945; BYTE $0xe5 // subl	%r12d, %r13d
	LONG $0x03e58341 // andl	$0x3, %r13d
	JE LBB0_13
LBB0_12:
	LONG $0x107aa1c4; WORD $0xa70c // vmovss	(%rdi,%r12,4), %xmm1
	LONG $0x5c72a1c4; WORD $0xa30c // vsubss	(%rbx,%r12,4), %xmm1, %xmm1
	LONG $0xb971e2c4; BYTE $0xc1 // vfmadd231ss	%xmm1, %xmm1, %xmm0 # xmm0 = (xmm1 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc4 // incq	%r12
	WORD $0xff49; BYTE $0xcd // decq	%r13
	JNE LBB0_12
LBB0_13:
	LONG $0xfcfe8348 // cmpq	$-0x4, %rsi
	JHI LBB0_15
LBB0_14:
	LONG $0x107aa1c4; WORD $0xa70c // vmovss	(%rdi,%r12,4), %xmm1
	LONG $0x107aa1c4; WORD $0xa754; BYTE $0x04 // vmovss	0x4(%rdi,%r12,4), %xmm2
	LONG $0x5c72a1c4; WORD $0xa30c // vsubss	(%rbx,%r12,4), %xmm1, %xmm1
	LONG $0x5c6aa1c4; WORD $0xa354; BYTE $0x04 // vsubss	0x4(%rbx,%r12,4), %xmm2, %xmm2
	LONG $0xa971e2c4; BYTE $0xc8 // vfmadd213ss	%xmm0, %xmm1, %xmm1 # xmm1 = (xmm1 * xmm1) + xmm0
	LONG $0x107aa1c4; WORD $0xa744; BYTE $0x08 // vmovss	0x8(%rdi,%r12,4), %xmm0
	LONG $0x5c7aa1c4; WORD $0xa35c; BYTE $0x08 // vsubss	0x8(%rbx,%r12,4), %xmm0, %xmm3
	LONG $0xa969e2c4; BYTE $0xd1 // vfmadd213ss	%xmm1, %xmm2, %xmm2 # xmm2 = (xmm2 * xmm2) + xmm1
	LONG $0x107aa1c4; WORD $0xa744; BYTE $0x0c // vmovss	0xc(%rdi,%r12,4), %xmm0
	LONG $0x5c7aa1c4; WORD $0xa344; BYTE $0x0c // vsubss	0xc(%rbx,%r12,4), %xmm0, %xmm0
	LONG $0xa961e2c4; BYTE $0xda // vfmadd213ss	%xmm2, %xmm3, %xmm3 # xmm3 = (xmm3 * xmm3) + xmm2
	LONG $0xa979e2c4; BYTE $0xc3 // vfmadd213ss	%xmm3, %xmm0, %xmm0 # xmm0 = (xmm0 * xmm0) + xmm3
	LONG $0x04c48349 // addq	$0x4, %r12
	WORD $0x394c; BYTE $0xe2 // cmpq	%r12, %rdx
	JNE LBB0_14
	JMP LBB0_15
LBB0_17:
	WORD $0x8949; BYTE $0xc6 // movq	%rax, %r14
	LONG $0xf0e68349 // andq	$-0x10, %r14
	WORD $0x8948; BYTE $0xc6 // movq	%rax, %rsi
	LONG $0x04eec148 // shrq	$0x4, %rsi
	WORD $0xff48; BYTE $0xc6 // incq	%rsi
	WORD $0x8949; BYTE $0xd1 // movq	%rdx, %r9
	WORD $0x294d; BYTE $0xf1 // subq	%r14, %r9
	LONG $0x10c68349 // addq	$0x10, %r14
	LONG $0xefc18349 // addq	$-0x11, %r9
	LONG $0x244c894c; BYTE $0x10 // movq	%r9, 0x10(%rsp)
	WORD $0x8941; BYTE $0xf5 // movl	%esi, %r13d
	LONG $0x03e58341 // andl	$0x3, %r13d
	LONG $0xfce68348 // andq	$-0x4, %rsi
	LONG $0x24748948; BYTE $0x18 // movq	%rsi, 0x18(%rsp)
	WORD $0xd689 // movl	%edx, %esi
	WORD $0xe683; BYTE $0x03 // andl	$0x3, %esi
	LONG $0x24748948; BYTE $0x08 // movq	%rsi, 0x8(%rsp)
	LONG $0x242c8b48 // movq	(%rsp), %rbp
	LONG $0xc0bd8d4c; WORD $0x0000; BYTE $0x00 // leaq	0xc0(%rbp), %r15
	QUAD $0x0000000095248d4c // leaq	(,%rdx,4), %r12
	LONG $0x246c894c; BYTE $0x20 // movq	%r13, 0x20(%rsp)
	LONG $0x06e5c141 // shll	$0x6, %r13d
	WORD $0x3145; BYTE $0xdb // xorl	%r11d, %r11d
	JMP LBB0_18
LBB0_53:
	LONG $0x117a81c4; WORD $0x9004 // vmovss	%xmm0, (%r8,%r10,4)
	WORD $0x014d; BYTE $0xe7 // addq	%r12, %r15
	WORD $0x014c; BYTE $0xe5 // addq	%r12, %rbp
	WORD $0x3949; BYTE $0xcb // cmpq	%rcx, %r11
	JE LBB0_54
LBB0_18:
	WORD $0x894d; BYTE $0xda // movq	%r11, %r10
	WORD $0xff49; BYTE $0xc3 // incq	%r11
	WORD $0x3949; BYTE $0xcb // cmpq	%rcx, %r11
	JGE LBB0_20
	WORD $0x894c; BYTE $0xde // movq	%r11, %rsi
	LONG $0xf2af0f48 // imulq	%rdx, %rsi
	LONG $0x240c8b4c // movq	(%rsp), %r9
	LONG $0x0c180f41; BYTE $0xb1 // prefetcht0	(%r9,%rsi,4)
LBB0_20:
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	LONG $0x30f88348 // cmpq	$0x30, %rax
	JCC LBB0_44
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	JMP LBB0_46
LBB0_44:
	LONG $0x24748b48; BYTE $0x18 // movq	0x18(%rsp), %rsi
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
LBB0_45:
	LONG $0x487cb162; WORD $0x0c10; BYTE $0x8f // vmovups	(%rdi,%r9,4), %zmm1
	QUAD $0x018f5410487cb162 // vmovups	0x40(%rdi,%r9,4), %zmm2
	QUAD $0x028f5c10487cb162 // vmovups	0x80(%rdi,%r9,4), %zmm3
	QUAD $0x038f6410487cb162 // vmovups	0xc0(%rdi,%r9,4), %zmm4
	QUAD $0xfd8f4c5c48749162 // vsubps	-0xc0(%r15,%r9,4), %zmm1, %zmm1
	LONG $0x4875f262; WORD $0xc8a8 // vfmadd213ps	%zmm0, %zmm1, %zmm1 # zmm1 = (zmm1 * zmm1) + zmm0
	QUAD $0xfe8f545c486c9162 // vsubps	-0x80(%r15,%r9,4), %zmm2, %zmm2
	LONG $0x486df262; WORD $0xd1a8 // vfmadd213ps	%zmm1, %zmm2, %zmm2 # zmm2 = (zmm2 * zmm2) + zmm1
	QUAD $0xff8f4c5c48649162 // vsubps	-0x40(%r15,%r9,4), %zmm3, %zmm1
	LONG $0x485c9162; WORD $0x045c; BYTE $0x8f // vsubps	(%r15,%r9,4), %zmm4, %zmm0
	LONG $0x4875f262; WORD $0xcaa8 // vfmadd213ps	%zmm2, %zmm1, %zmm1 # zmm1 = (zmm1 * zmm1) + zmm2
	LONG $0x487df262; WORD $0xc1a8 // vfmadd213ps	%zmm1, %zmm0, %zmm0 # zmm0 = (zmm0 * zmm0) + zmm1
	LONG $0x40c18349 // addq	$0x40, %r9
	LONG $0xfcc68348 // addq	$-0x4, %rsi
	JNE LBB0_45
LBB0_46:
	LONG $0x247c8348; WORD $0x0020 // cmpq	$0x0, 0x20(%rsp)
	JE LBB0_49
	QUAD $0x000000008d348d4a // leaq	(,%r9,4), %rsi
	WORD $0x0148; BYTE $0xee // addq	%rbp, %rsi
	LONG $0x8f0c8d4e // leaq	(%rdi,%r9,4), %r9
	WORD $0xdb31 // xorl	%ebx, %ebx
LBB0_48:
	LONG $0x487cd162; WORD $0x0c10; BYTE $0x19 // vmovups	(%r9,%rbx), %zmm1
	LONG $0x4874f162; WORD $0x0c5c; BYTE $0x1e // vsubps	(%rsi,%rbx), %zmm1, %zmm1
	LONG $0x4875f262; WORD $0xc1b8 // vfmadd231ps	%zmm1, %zmm1, %zmm0 # zmm0 = (zmm1 * zmm1) + zmm0
	LONG $0x40c38348 // addq	$0x40, %rbx
	WORD $0x3949; BYTE $0xdd // cmpq	%rbx, %r13
	JNE LBB0_48
LBB0_49:
	LONG $0x48fdf362; WORD $0xc11b; BYTE $0x01 // vextractf64x4	$0x1, %zmm0, %ymm1
	LONG $0x487cf162; WORD $0xc158 // vaddps	%zmm1, %zmm0, %zmm0
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc8c6f9c5; BYTE $0x01 // vshufpd	$0x1, %xmm0, %xmm0, %xmm1 # xmm1 = xmm0[1,0]
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc816fac5 // vmovshdup	%xmm0, %xmm1    # xmm1 = xmm0[1,1,3,3]
	LONG $0xc158fac5 // vaddss	%xmm1, %xmm0, %xmm0
	WORD $0x3949; BYTE $0xd6 // cmpq	%rdx, %r14
	JGE LBB0_53
	LONG $0x24748b48; BYTE $0x08 // movq	0x8(%rsp), %rsi
	WORD $0x894d; BYTE $0xf1 // movq	%r14, %r9
	WORD $0x8548; BYTE $0xf6 // testq	%rsi, %rsi
	JE LBB0_52
LBB0_51:
	LONG $0x107aa1c4; WORD $0x8f0c // vmovss	(%rdi,%r9,4), %xmm1
	LONG $0x5c72a1c4; WORD $0x8d4c; BYTE $0x00 // vsubss	(%rbp,%r9,4), %xmm1, %xmm1
	LONG $0xb971e2c4; BYTE $0xc1 // vfmadd231ss	%xmm1, %xmm1, %xmm0 # xmm0 = (xmm1 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc1 // incq	%r9
	WORD $0xff48; BYTE $0xce // decq	%rsi
	JNE LBB0_51
LBB0_52:
	LONG $0x247c8348; WORD $0x0310 // cmpq	$0x3, 0x10(%rsp)
	JCS LBB0_53
LBB0_55:
	LONG $0x107aa1c4; WORD $0x8f0c // vmovss	(%rdi,%r9,4), %xmm1
	LONG $0x107aa1c4; WORD $0x8f54; BYTE $0x04 // vmovss	0x4(%rdi,%r9,4), %xmm2
	LONG $0x5c72a1c4; WORD $0x8d4c; BYTE $0x00 // vsubss	(%rbp,%r9,4), %xmm1, %xmm1
	LONG $0x5c6aa1c4; WORD $0x8d54; BYTE $0x04 // vsubss	0x4(%rbp,%r9,4), %xmm2, %xmm2
	LONG $0xa971e2c4; BYTE $0xc8 // vfmadd213ss	%xmm0, %xmm1, %xmm1 # xmm1 = (xmm1 * xmm1) + xmm0
	LONG $0x107aa1c4; WORD $0x8f44; BYTE $0x08 // vmovss	0x8(%rdi,%r9,4), %xmm0
	LONG $0x5c7aa1c4; WORD $0x8d5c; BYTE $0x08 // vsubss	0x8(%rbp,%r9,4), %xmm0, %xmm3
	LONG $0xa969e2c4; BYTE $0xd1 // vfmadd213ss	%xmm1, %xmm2, %xmm2 # xmm2 = (xmm2 * xmm2) + xmm1
	LONG $0x107aa1c4; WORD $0x8f44; BYTE $0x0c // vmovss	0xc(%rdi,%r9,4), %xmm0
	LONG $0x5c7aa1c4; WORD $0x8d44; BYTE $0x0c // vsubss	0xc(%rbp,%r9,4), %xmm0, %xmm0
	LONG $0xa961e2c4; BYTE $0xda // vfmadd213ss	%xmm2, %xmm3, %xmm3 # xmm3 = (xmm3 * xmm3) + xmm2
	LONG $0xa979e2c4; BYTE $0xc3 // vfmadd213ss	%xmm3, %xmm0, %xmm0 # xmm0 = (xmm0 * xmm0) + xmm3
	LONG $0x04c18349 // addq	$0x4, %r9
	WORD $0x394c; BYTE $0xca // cmpq	%r9, %rdx
	JNE LBB0_55
	JMP LBB0_53
LBB0_23:
	LONG $0x01f98348 // cmpq	$0x1, %rcx
	JNE LBB0_34
	WORD $0xf631 // xorl	%esi, %esi
LBB0_40:
	WORD $0xc1f6; BYTE $0x01 // testb	$0x1, %cl
	JE LBB0_54
	LONG $0x01468d48 // leaq	0x1(%rsi), %rax
	WORD $0x3948; BYTE $0xc8 // cmpq	%rcx, %rax
	JGE LBB0_43
	LONG $0xc2af0f48 // imulq	%rdx, %rax
	LONG $0x240c8b48 // movq	(%rsp), %rcx
	LONG $0x810c180f // prefetcht0	(%rcx,%rax,4)
LBB0_43:
	QUAD $0x00000000b004c741 // movl	$0x0, (%r8,%rsi,4)
LBB0_54:
	LONG $0x28c48348 // addq	$0x28, %rsp
	BYTE $0x5b // popq	%rbx
	WORD $0x5c41 // popq	%r12
	WORD $0x5d41 // popq	%r13
	WORD $0x5e41 // popq	%r14
	WORD $0x5f41 // popq	%r15
	BYTE $0x5d // popq	%rbp
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET
LBB0_34:
	QUAD $0xfffffffffffcb848; WORD $0x7fff // movabsq	$0x7ffffffffffffffc, %rax # imm = 0x7FFFFFFFFFFFFFFC
	LONG $0x02c88348 // orq	$0x2, %rax
	WORD $0x2148; BYTE $0xc8 // andq	%rcx, %rax
	QUAD $0x00000000953c8d48 // leaq	(,%rdx,4), %rdi
	QUAD $0x00000000d50c8d4c // leaq	(,%rdx,8), %r9
	WORD $0x3145; BYTE $0xdb // xorl	%r11d, %r11d
	LONG $0x24148b4c // movq	(%rsp), %r10
	JMP LBB0_35
LBB0_39:
	QUAD $0x000000049844c743; BYTE $0x00 // movl	$0x0, 0x4(%r8,%r11,4)
	WORD $0x014d; BYTE $0xca // addq	%r9, %r10
	WORD $0x8949; BYTE $0xf3 // movq	%rsi, %r11
	WORD $0x3948; BYTE $0xf0 // cmpq	%rsi, %rax
	JE LBB0_40
LBB0_35:
	LONG $0x01738d49 // leaq	0x1(%r11), %rsi
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JGE LBB0_37
	LONG $0x0c180f41; BYTE $0x3a // prefetcht0	(%r10,%rdi)
LBB0_37:
	QUAD $0x000000009804c743 // movl	$0x0, (%r8,%r11,4)
	LONG $0x02738d49 // leaq	0x2(%r11), %rsi
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JGE LBB0_39
	LONG $0x0c180f43; BYTE $0x0a // prefetcht0	(%r10,%r9)
	JMP LBB0_39

