// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func dotBatchNeon(query unsafe.Pointer, targets unsafe.Pointer, dim int64, n int64, out unsafe.Pointer)

//go:noescape
func squaredL2BatchNeon(query unsafe.Pointer, targets unsafe.Pointer, dim int64, n int64, out unsafe.Pointer)

