// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func andNotWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func andWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func orWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func xorWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

