// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·andNotWordsAVX2Asm(SB), NOSPLIT, $0-24
	MOVQ dst+0(FP), DI
	MOVQ src+8(FP), SI
	MOVQ n+16(FP), DX

	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JGE LBB1_2
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB1_7
LBB1_2:
	LONG $0xfc4a8d48 // leaq	-0x4(%rdx), %rcx
	LONG $0x04f98348 // cmpq	$0x4, %rcx
	JAE LBB1_13
	LONG $0x0004b841; WORD $0x0000 // movl	$0x4, %r8d
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0xc1f6; BYTE $0x04 // testb	$0x4, %cl
	JE LBB1_6
	JMP LBB1_7
LBB1_13:
	WORD $0x8948; BYTE $0xc8 // movq	%rcx, %rax
	LONG $0x02e8c148 // shrq	$0x2, %rax
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	LONG $0xfee08348 // andq	$-0x2, %rax
	LONG $0x0004b841; WORD $0x0000 // movl	$0x4, %r8d
LBB1_14:
	LONG $0x107ca1c4; WORD $0xc644; BYTE $0xe0 // vmovups	-0x20(%rsi,%r8,8), %ymm0
	LONG $0x557ca1c4; WORD $0xc744; BYTE $0xe0 // vandnps	-0x20(%rdi,%r8,8), %ymm0, %ymm0
	LONG $0x117ca1c4; WORD $0xc744; BYTE $0xe0 // vmovups	%ymm0, -0x20(%rdi,%r8,8)
	LONG $0x107ca1c4; WORD $0xc604 // vmovups	(%rsi,%r8,8), %ymm0
	LONG $0x557ca1c4; WORD $0xc704 // vandnps	(%rdi,%r8,8), %ymm0, %ymm0
	LONG $0x117ca1c4; WORD $0xc704 // vmovups	%ymm0, (%rdi,%r8,8)
	LONG $0x08c08349 // addq	$0x8, %r8
	LONG $0xfec08348 // addq	$-0x2, %rax
	JNE LBB1_14
	LONG $0xfc408d49 // leaq	-0x4(%r8), %rax
	WORD $0xc1f6; BYTE $0x04 // testb	$0x4, %cl
	JNE LBB1_7
LBB1_6:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0455fcc5; BYTE $0xc7 // vandnps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
LBB1_7:
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JLE LBB1_12
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc0 // subl	%eax, %r8d
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0x01c0f641 // testb	$0x1, %r8b
	JE LBB1_10
	LONG $0xc60c8b48 // movq	(%rsi,%rax,8), %rcx
	WORD $0xf748; BYTE $0xd1 // notq	%rcx
	LONG $0xc70c2148 // andq	%rcx, (%rdi,%rax,8)
	LONG $0x01488d48 // leaq	0x1(%rax), %rcx
LBB1_10:
	LONG $0xff428d4c // leaq	-0x1(%rdx), %r8
	WORD $0x394c; BYTE $0xc0 // cmpq	%r8, %rax
	JE LBB1_12
LBB1_11:
	LONG $0xce048b48 // movq	(%rsi,%rcx,8), %rax
	WORD $0xf748; BYTE $0xd0 // notq	%rax
	LONG $0xcf042148 // andq	%rax, (%rdi,%rcx,8)
	LONG $0xce448b48; BYTE $0x08 // movq	0x8(%rsi,%rcx,8), %rax
	WORD $0xf748; BYTE $0xd0 // notq	%rax
	LONG $0xcf442148; BYTE $0x08 // andq	%rax, 0x8(%rdi,%rcx,8)
	LONG $0x02c18348 // addq	$0x2, %rcx
	WORD $0x3948; BYTE $0xca // cmpq	%rcx, %rdx
	JNE LBB1_11
LBB1_12:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·andWordsAVX2Asm(SB), NOSPLIT, $0-24
	MOVQ dst+0(FP), DI
	MOVQ src+8(FP), SI
	MOVQ n+16(FP), DX

	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JGE LBB0_2
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB0_8
LBB0_2:
	LONG $0xfc428d48 // leaq	-0x4(%rdx), %rax
	WORD $0x8949; BYTE $0xc0 // movq	%rax, %r8
	LONG $0x02e8c149 // shrq	$0x2, %r8
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x8944; BYTE $0xc1 // movl	%r8d, %ecx
	WORD $0xe183; BYTE $0x03 // andl	$0x3, %ecx
	LONG $0x0cf88348 // cmpq	$0xc, %rax
	JAE LBB0_14
	LONG $0x0004b841; WORD $0x0000 // movl	$0x4, %r8d
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JNE LBB0_6
	JMP LBB0_8
LBB0_14:
	LONG $0xfce08349 // andq	$-0x4, %r8
	WORD $0xc031 // xorl	%eax, %eax
LBB0_15:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0454fcc5; BYTE $0xc7 // vandps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x20c6 // vmovups	0x20(%rsi,%rax,8), %ymm0
	LONG $0x4454fcc5; WORD $0x20c7 // vandps	0x20(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x20c7 // vmovups	%ymm0, 0x20(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x40c6 // vmovups	0x40(%rsi,%rax,8), %ymm0
	LONG $0x4454fcc5; WORD $0x40c7 // vandps	0x40(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x40c7 // vmovups	%ymm0, 0x40(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x60c6 // vmovups	0x60(%rsi,%rax,8), %ymm0
	LONG $0x4454fcc5; WORD $0x60c7 // vandps	0x60(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x60c7 // vmovups	%ymm0, 0x60(%rdi,%rax,8)
	LONG $0x10c08348 // addq	$0x10, %rax
	LONG $0xfcc08349 // addq	$-0x4, %r8
	JNE LBB0_15
	LONG $0x04408d4c // leaq	0x4(%rax), %r8
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JE LBB0_8
LBB0_6:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0454fcc5; BYTE $0xc7 // vandps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
	LONG $0x04c08349 // addq	$0x4, %r8
	WORD $0xff48; BYTE $0xc9 // decq	%rcx
	JNE LBB0_6
	LONG $0xfcc08349 // addq	$-0x4, %r8
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
LBB0_8:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	WORD $0x2948; BYTE $0xd1 // subq	%rdx, %rcx
	JGE LBB0_13
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc0 // subl	%eax, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	JE LBB0_11
LBB0_10:
	LONG $0xc60c8b4c // movq	(%rsi,%rax,8), %r9
	LONG $0xc70c214c // andq	%r9, (%rdi,%rax,8)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB0_10
LBB0_11:
	LONG $0xfcf98348 // cmpq	$-0x4, %rcx
	JHI LBB0_13
LBB0_12:
	LONG $0xc60c8b48 // movq	(%rsi,%rax,8), %rcx
	LONG $0xc70c2148 // andq	%rcx, (%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x08 // movq	0x8(%rsi,%rax,8), %rcx
	LONG $0xc74c2148; BYTE $0x08 // andq	%rcx, 0x8(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x10 // movq	0x10(%rsi,%rax,8), %rcx
	LONG $0xc74c2148; BYTE $0x10 // andq	%rcx, 0x10(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x18 // movq	0x18(%rsi,%rax,8), %rcx
	LONG $0xc74c2148; BYTE $0x18 // andq	%rcx, 0x18(%rdi,%rax,8)
	LONG $0x04c08348 // addq	$0x4, %rax
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JNE LBB0_12
LBB0_13:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·orWordsAVX2Asm(SB), NOSPLIT, $0-24
	MOVQ dst+0(FP), DI
	MOVQ src+8(FP), SI
	MOVQ n+16(FP), DX

	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JGE LBB2_2
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB2_8
LBB2_2:
	LONG $0xfc428d48 // leaq	-0x4(%rdx), %rax
	WORD $0x8949; BYTE $0xc0 // movq	%rax, %r8
	LONG $0x02e8c149 // shrq	$0x2, %r8
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x8944; BYTE $0xc1 // movl	%r8d, %ecx
	WORD $0xe183; BYTE $0x03 // andl	$0x3, %ecx
	LONG $0x0cf88348 // cmpq	$0xc, %rax
	JAE LBB2_14
	LONG $0x0004b841; WORD $0x0000 // movl	$0x4, %r8d
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JNE LBB2_6
	JMP LBB2_8
LBB2_14:
	LONG $0xfce08349 // andq	$-0x4, %r8
	WORD $0xc031 // xorl	%eax, %eax
LBB2_15:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0456fcc5; BYTE $0xc7 // vorps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x20c6 // vmovups	0x20(%rsi,%rax,8), %ymm0
	LONG $0x4456fcc5; WORD $0x20c7 // vorps	0x20(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x20c7 // vmovups	%ymm0, 0x20(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x40c6 // vmovups	0x40(%rsi,%rax,8), %ymm0
	LONG $0x4456fcc5; WORD $0x40c7 // vorps	0x40(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x40c7 // vmovups	%ymm0, 0x40(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x60c6 // vmovups	0x60(%rsi,%rax,8), %ymm0
	LONG $0x4456fcc5; WORD $0x60c7 // vorps	0x60(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x60c7 // vmovups	%ymm0, 0x60(%rdi,%rax,8)
	LONG $0x10c08348 // addq	$0x10, %rax
	LONG $0xfcc08349 // addq	$-0x4, %r8
	JNE LBB2_15
	LONG $0x04408d4c // leaq	0x4(%rax), %r8
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JE LBB2_8
LBB2_6:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0456fcc5; BYTE $0xc7 // vorps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
	LONG $0x04c08349 // addq	$0x4, %r8
	WORD $0xff48; BYTE $0xc9 // decq	%rcx
	JNE LBB2_6
	LONG $0xfcc08349 // addq	$-0x4, %r8
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
LBB2_8:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	WORD $0x2948; BYTE $0xd1 // subq	%rdx, %rcx
	JGE LBB2_13
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc0 // subl	%eax, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	JE LBB2_11
LBB2_10:
	LONG $0xc60c8b4c // movq	(%rsi,%rax,8), %r9
	LONG $0xc70c094c // orq	%r9, (%rdi,%rax,8)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB2_10
LBB2_11:
	LONG $0xfcf98348 // cmpq	$-0x4, %rcx
	JHI LBB2_13
LBB2_12:
	LONG $0xc60c8b48 // movq	(%rsi,%rax,8), %rcx
	LONG $0xc70c0948 // orq	%rcx, (%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x08 // movq	0x8(%rsi,%rax,8), %rcx
	LONG $0xc74c0948; BYTE $0x08 // orq	%rcx, 0x8(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x10 // movq	0x10(%rsi,%rax,8), %rcx
	LONG $0xc74c0948; BYTE $0x10 // orq	%rcx, 0x10(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x18 // movq	0x18(%rsi,%rax,8), %rcx
	LONG $0xc74c0948; BYTE $0x18 // orq	%rcx, 0x18(%rdi,%rax,8)
	LONG $0x04c08348 // addq	$0x4, %rax
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JNE LBB2_12
LBB2_13:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·xorWordsAVX2Asm(SB), NOSPLIT, $0-24
	MOVQ dst+0(FP), DI
	MOVQ src+8(FP), SI
	MOVQ n+16(FP), DX

	LONG $0x04fa8348 // cmpq	$0x4, %rdx
	JGE LBB3_2
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB3_8
LBB3_2:
	LONG $0xfc428d48 // leaq	-0x4(%rdx), %rax
	WORD $0x8949; BYTE $0xc0 // movq	%rax, %r8
	LONG $0x02e8c149 // shrq	$0x2, %r8
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x8944; BYTE $0xc1 // movl	%r8d, %ecx
	WORD $0xe183; BYTE $0x03 // andl	$0x3, %ecx
	LONG $0x0cf88348 // cmpq	$0xc, %rax
	JAE LBB3_14
	LONG $0x0004b841; WORD $0x0000 // movl	$0x4, %r8d
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JNE LBB3_6
	JMP LBB3_8
LBB3_14:
	LONG $0xfce08349 // andq	$-0x4, %r8
	WORD $0xc031 // xorl	%eax, %eax
LBB3_15:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0457fcc5; BYTE $0xc7 // vxorps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x20c6 // vmovups	0x20(%rsi,%rax,8), %ymm0
	LONG $0x4457fcc5; WORD $0x20c7 // vxorps	0x20(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x20c7 // vmovups	%ymm0, 0x20(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x40c6 // vmovups	0x40(%rsi,%rax,8), %ymm0
	LONG $0x4457fcc5; WORD $0x40c7 // vxorps	0x40(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x40c7 // vmovups	%ymm0, 0x40(%rdi,%rax,8)
	LONG $0x4410fcc5; WORD $0x60c6 // vmovups	0x60(%rsi,%rax,8), %ymm0
	LONG $0x4457fcc5; WORD $0x60c7 // vxorps	0x60(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x4411fcc5; WORD $0x60c7 // vmovups	%ymm0, 0x60(%rdi,%rax,8)
	LONG $0x10c08348 // addq	$0x10, %rax
	LONG $0xfcc08349 // addq	$-0x4, %r8
	JNE LBB3_15
	LONG $0x04408d4c // leaq	0x4(%rax), %r8
	WORD $0x8548; BYTE $0xc9 // testq	%rcx, %rcx
	JE LBB3_8
LBB3_6:
	LONG $0x0410fcc5; BYTE $0xc6 // vmovups	(%rsi,%rax,8), %ymm0
	LONG $0x0457fcc5; BYTE $0xc7 // vxorps	(%rdi,%rax,8), %ymm0, %ymm0
	LONG $0x0411fcc5; BYTE $0xc7 // vmovups	%ymm0, (%rdi,%rax,8)
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
	LONG $0x04c08349 // addq	$0x4, %r8
	WORD $0xff48; BYTE $0xc9 // decq	%rcx
	JNE LBB3_6
	LONG $0xfcc08349 // addq	$-0x4, %r8
	WORD $0x894c; BYTE $0xc0 // movq	%r8, %rax
LBB3_8:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	WORD $0x2948; BYTE $0xd1 // subq	%rdx, %rcx
	JGE LBB3_13
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc0 // subl	%eax, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	JE LBB3_11
LBB3_10:
	LONG $0xc60c8b4c // movq	(%rsi,%rax,8), %r9
	LONG $0xc70c314c // xorq	%r9, (%rdi,%rax,8)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB3_10
LBB3_11:
	LONG $0xfcf98348 // cmpq	$-0x4, %rcx
	JHI LBB3_13
LBB3_12:
	LONG $0xc60c8b48 // movq	(%rsi,%rax,8), %rcx
	LONG $0xc70c3148 // xorq	%rcx, (%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x08 // movq	0x8(%rsi,%rax,8), %rcx
	LONG $0xc74c3148; BYTE $0x08 // xorq	%rcx, 0x8(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x10 // movq	0x10(%rsi,%rax,8), %rcx
	LONG $0xc74c3148; BYTE $0x10 // xorq	%rcx, 0x10(%rdi,%rax,8)
	LONG $0xc64c8b48; BYTE $0x18 // movq	0x18(%rsi,%rax,8), %rcx
	LONG $0xc74c3148; BYTE $0x18 // xorq	%rcx, 0x18(%rdi,%rax,8)
	LONG $0x04c08348 // addq	$0x4, %rax
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JNE LBB3_12
LBB3_13:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

