// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func andNotWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func andWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func orWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func xorWordsNEONAsm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

// NOTE: popcountWordsNEONAsm removed - Go's bits.OnesCount64 compiles to hardware
// CNT instruction and is faster than explicit SIMD due to reduced overhead.
