// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func andNotWordsAVX512Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func andWordsAVX512Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func orWordsAVX512Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func xorWordsAVX512Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

