// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func andNotWordsSVE2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func andWordsSVE2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func orWordsSVE2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func xorWordsSVE2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

// NOTE: popcountWordsSVE2Asm removed - Go's bits.OnesCount64 compiles to hardware
// CNT instruction and is faster than explicit SIMD due to reduced overhead.
