// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func andNotWordsAVX2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func andWordsAVX2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func orWordsAVX2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

//go:noescape
func xorWordsAVX2Asm(dst unsafe.Pointer, src unsafe.Pointer, n int64)

// NOTE: popcountWordsAVX2Asm removed - Go's bits.OnesCount64 compiles to hardware
// POPCNT instruction and is faster than explicit SIMD due to reduced overhead.
