// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func squaredL2BoundedAvx512(vec1 unsafe.Pointer, vec2 unsafe.Pointer, n int64, bound float32, result unsafe.Pointer, exceeded unsafe.Pointer)

