// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func f16ToF32Avx512(in unsafe.Pointer, out unsafe.Pointer, n int64)

