// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func countRangeF64Avx(values unsafe.Pointer, n int64, minVal float64, maxVal float64) int64

//go:noescape
func filterRangeF64Avx(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer)

//go:noescape
func filterRangeF64IndicesAvx(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer) int64

//go:noescape
func gatherU32Avx(src unsafe.Pointer, indices unsafe.Pointer, n int64, dst unsafe.Pointer)

