// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·countRangeF64Avx2(SB), NOSPLIT, $0-40
	MOVQ values+0(FP), DI
	MOVQ n+8(FP), SI
	MOVSD minVal+16(FP), X0
	MOVSD maxVal+24(FP), X1
	MOVQ countOut+32(FP), DX

	LONG $0x04fe8348 // cmpq	$0x4, %rsi
	JGE LBB2_2
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB2_7
LBB2_2:
	LONG $0x197de2c4; BYTE $0xd0 // vbroadcastsd	%xmm0, %ymm2
	LONG $0x197de2c4; BYTE $0xd9 // vbroadcastsd	%xmm1, %ymm3
	LONG $0xfc468d4c // leaq	-0x4(%rsi), %r8
	LONG $0x04f88349 // cmpq	$0x4, %r8
	JCC LBB2_14
	LONG $0x000004b9; BYTE $0x00 // movl	$0x4, %ecx
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	LONG $0x04c0f641 // testb	$0x4, %r8b
	JE LBB2_6
	JMP LBB2_7
LBB2_14:
	WORD $0x894d; BYTE $0xc1 // movq	%r8, %r9
	LONG $0x02e9c149 // shrq	$0x2, %r9
	WORD $0xff49; BYTE $0xc1 // incq	%r9
	LONG $0xfee18349 // andq	$-0x2, %r9
	LONG $0x000004b9; BYTE $0x00 // movl	$0x4, %ecx
	WORD $0xc031 // xorl	%eax, %eax
LBB2_15:
	LONG $0x6410fdc5; WORD $0xe0cf // vmovupd	-0x20(%rdi,%rcx,8), %ymm4
	LONG $0x2c10fdc5; BYTE $0xcf // vmovupd	(%rdi,%rcx,8), %ymm5
	LONG $0xf3c2ddc5; BYTE $0x02 // vcmplepd	%ymm3, %ymm4, %ymm6
	LONG $0xe4c2edc5; BYTE $0x02 // vcmplepd	%ymm4, %ymm2, %ymm4
	LONG $0xe654ddc5 // vandpd	%ymm6, %ymm4, %ymm4
	LONG $0xd4507dc5 // vmovmskpd	%ymm4, %r10d
	LONG $0xb80f45f3; BYTE $0xd2 // popcntl	%r10d, %r10d
	WORD $0x0149; BYTE $0xc2 // addq	%rax, %r10
	LONG $0xe3c2d5c5; BYTE $0x02 // vcmplepd	%ymm3, %ymm5, %ymm4
	LONG $0xedc2edc5; BYTE $0x02 // vcmplepd	%ymm5, %ymm2, %ymm5
	LONG $0xe454d5c5 // vandpd	%ymm4, %ymm5, %ymm4
	LONG $0xc450fdc5 // vmovmskpd	%ymm4, %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	WORD $0x014c; BYTE $0xd0 // addq	%r10, %rax
	LONG $0x08c18348 // addq	$0x8, %rcx
	LONG $0xfec18349 // addq	$-0x2, %r9
	JNE LBB2_15
	LONG $0xfc498d4c // leaq	-0x4(%rcx), %r9
	LONG $0x04c0f641 // testb	$0x4, %r8b
	JNE LBB2_7
LBB2_6:
	LONG $0x107da1c4; WORD $0xcf24 // vmovupd	(%rdi,%r9,8), %ymm4
	LONG $0xdbc2ddc5; BYTE $0x02 // vcmplepd	%ymm3, %ymm4, %ymm3
	LONG $0xd4c2edc5; BYTE $0x02 // vcmplepd	%ymm4, %ymm2, %ymm2
	LONG $0xd354edc5 // vandpd	%ymm3, %ymm2, %ymm2
	LONG $0xc2507dc5 // vmovmskpd	%ymm2, %r8d
	LONG $0xb80f45f3; BYTE $0xc0 // popcntl	%r8d, %r8d
	WORD $0x014c; BYTE $0xc0 // addq	%r8, %rax
	WORD $0x8949; BYTE $0xc9 // movq	%rcx, %r9
LBB2_7:
	WORD $0x394c; BYTE $0xce // cmpq	%r9, %rsi
	JLE LBB2_13
	WORD $0xf189 // movl	%esi, %ecx
	WORD $0x2944; BYTE $0xc9 // subl	%r9d, %ecx
	WORD $0xc1f6; BYTE $0x01 // testb	$0x1, %cl
	JNE LBB2_10
	WORD $0x894c; BYTE $0xc9 // movq	%r9, %rcx
	LONG $0xff468d4c // leaq	-0x1(%rsi), %r8
	WORD $0x394d; BYTE $0xc1 // cmpq	%r8, %r9
	JNE LBB2_12
	JMP LBB2_13
LBB2_10:
	LONG $0x107ba1c4; WORD $0xcf14 // vmovsd	(%rdi,%r9,8), %xmm2
	LONG $0xd9c2e9c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm2, %xmm3
	LONG $0xd2c2f9c5; BYTE $0x02 // vcmplepd	%xmm2, %xmm0, %xmm2
	LONG $0xd354e9c5 // vandpd	%xmm3, %xmm2, %xmm2
	LONG $0x7ef9e1c4; BYTE $0xd1 // vmovq	%xmm2, %rcx
	WORD $0x2948; BYTE $0xc8 // subq	%rcx, %rax
	LONG $0x01498d49 // leaq	0x1(%r9), %rcx
	LONG $0xff468d4c // leaq	-0x1(%rsi), %r8
	WORD $0x394d; BYTE $0xc1 // cmpq	%r8, %r9
	JE LBB2_13
LBB2_12:
	LONG $0x1410fbc5; BYTE $0xcf // vmovsd	(%rdi,%rcx,8), %xmm2
	LONG $0x5c10fbc5; WORD $0x08cf // vmovsd	0x8(%rdi,%rcx,8), %xmm3
	LONG $0xe1c2e9c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm2, %xmm4
	LONG $0xd2c2f9c5; BYTE $0x02 // vcmplepd	%xmm2, %xmm0, %xmm2
	LONG $0xd454e9c5 // vandpd	%xmm4, %xmm2, %xmm2
	LONG $0x7ef9c1c4; BYTE $0xd0 // vmovq	%xmm2, %r8
	WORD $0x294c; BYTE $0xc0 // subq	%r8, %rax
	LONG $0xd1c2e1c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm3, %xmm2
	LONG $0xdbc2f9c5; BYTE $0x02 // vcmplepd	%xmm3, %xmm0, %xmm3
	LONG $0xd254e1c5 // vandpd	%xmm2, %xmm3, %xmm2
	LONG $0x7ef9c1c4; BYTE $0xd0 // vmovq	%xmm2, %r8
	WORD $0x294c; BYTE $0xc0 // subq	%r8, %rax
	LONG $0x02c18348 // addq	$0x2, %rcx
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JNE LBB2_12
LBB2_13:
	WORD $0x8948; BYTE $0x02 // movq	%rax, (%rdx)
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·filterRangeF64Avx2(SB), NOSPLIT, $0-40
	MOVQ values+0(FP), DI
	MOVQ n+8(FP), SI
	MOVSD minVal+16(FP), X0
	MOVSD maxVal+24(FP), X1
	MOVQ dst+32(FP), DX

	LONG $0x04fe8348 // cmpq	$0x4, %rsi
	JGE LBB0_8
	WORD $0xc931 // xorl	%ecx, %ecx
	JMP LBB0_2
LBB0_8:
	LONG $0x197de2c4; BYTE $0xd0 // vbroadcastsd	%xmm0, %ymm2
	LONG $0x197de2c4; BYTE $0xd9 // vbroadcastsd	%xmm1, %ymm3
	WORD $0xc031 // xorl	%eax, %eax
LBB0_9:
	LONG $0x2410fdc5; BYTE $0xc7 // vmovupd	(%rdi,%rax,8), %ymm4
	LONG $0xebc2ddc5; BYTE $0x02 // vcmplepd	%ymm3, %ymm4, %ymm5
	LONG $0xe4c2edc5; BYTE $0x02 // vcmplepd	%ymm4, %ymm2, %ymm4
	LONG $0xe554ddc5 // vandpd	%ymm5, %ymm4, %ymm4
	LONG $0xcc50fdc5 // vmovmskpd	%ymm4, %ecx
	WORD $0x8941; BYTE $0xc8 // movl	%ecx, %r8d
	LONG $0x01e08041 // andb	$0x1, %r8b
	LONG $0x02048844 // movb	%r8b, (%rdx,%rax)
	WORD $0x8941; BYTE $0xc8 // movl	%ecx, %r8d
	WORD $0xd041; BYTE $0xe8 // shrb	%r8b
	LONG $0x01e08041 // andb	$0x1, %r8b
	LONG $0x02448844; BYTE $0x01 // movb	%r8b, 0x1(%rdx,%rax)
	WORD $0x8941; BYTE $0xc8 // movl	%ecx, %r8d
	LONG $0x02e8c041 // shrb	$0x2, %r8b
	LONG $0x01e08041 // andb	$0x1, %r8b
	LONG $0x02448844; BYTE $0x02 // movb	%r8b, 0x2(%rdx,%rax)
	WORD $0xe9c0; BYTE $0x03 // shrb	$0x3, %cl
	LONG $0x03024c88 // movb	%cl, 0x3(%rdx,%rax)
	LONG $0x04488d48 // leaq	0x4(%rax), %rcx
	LONG $0x08c08348 // addq	$0x8, %rax
	WORD $0x3948; BYTE $0xf0 // cmpq	%rsi, %rax
	WORD $0x8948; BYTE $0xc8 // movq	%rcx, %rax
	JLE LBB0_9
LBB0_2:
	WORD $0x3948; BYTE $0xf1 // cmpq	%rsi, %rcx
	JGE LBB0_7
	WORD $0x8948; BYTE $0xc8 // movq	%rcx, %rax
	LONG $0x01c6f640 // testb	$0x1, %sil
	JE LBB0_5
	LONG $0x1410fbc5; BYTE $0xcf // vmovsd	(%rdi,%rcx,8), %xmm2
	LONG $0xd9c2e9c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm2, %xmm3
	LONG $0xd2c2f9c5; BYTE $0x02 // vcmplepd	%xmm2, %xmm0, %xmm2
	LONG $0xd354e9c5 // vandpd	%xmm3, %xmm2, %xmm2
	LONG $0xd07ef9c5 // vmovd	%xmm2, %eax
	WORD $0x0124 // andb	$0x1, %al
	WORD $0x0488; BYTE $0x0a // movb	%al, (%rdx,%rcx)
	WORD $0x8948; BYTE $0xc8 // movq	%rcx, %rax
	LONG $0x01c88348 // orq	$0x1, %rax
LBB0_5:
	LONG $0xff468d4c // leaq	-0x1(%rsi), %r8
	WORD $0x394c; BYTE $0xc1 // cmpq	%r8, %rcx
	JE LBB0_7
LBB0_6:
	LONG $0x1410fbc5; BYTE $0xc7 // vmovsd	(%rdi,%rax,8), %xmm2
	LONG $0xd9c2e9c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm2, %xmm3
	LONG $0xd2c2f9c5; BYTE $0x02 // vcmplepd	%xmm2, %xmm0, %xmm2
	LONG $0xd354e9c5 // vandpd	%xmm3, %xmm2, %xmm2
	LONG $0xd17ef9c5 // vmovd	%xmm2, %ecx
	WORD $0xe180; BYTE $0x01 // andb	$0x1, %cl
	WORD $0x0c88; BYTE $0x02 // movb	%cl, (%rdx,%rax)
	LONG $0x5410fbc5; WORD $0x08c7 // vmovsd	0x8(%rdi,%rax,8), %xmm2
	LONG $0xd9c2e9c5; BYTE $0x02 // vcmplepd	%xmm1, %xmm2, %xmm3
	LONG $0xd2c2f9c5; BYTE $0x02 // vcmplepd	%xmm2, %xmm0, %xmm2
	LONG $0xd354e9c5 // vandpd	%xmm3, %xmm2, %xmm2
	LONG $0xd17ef9c5 // vmovd	%xmm2, %ecx
	WORD $0xe180; BYTE $0x01 // andb	$0x1, %cl
	LONG $0x01024c88 // movb	%cl, 0x1(%rdx,%rax)
	LONG $0x02c08348 // addq	$0x2, %rax
	WORD $0x3948; BYTE $0xc6 // cmpq	%rax, %rsi
	JNE LBB0_6
LBB0_7:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·filterRangeF64IndicesAvx2(SB), NOSPLIT, $0-48
	MOVQ values+0(FP), DI
	MOVQ n+8(FP), SI
	MOVSD minVal+16(FP), X0
	MOVSD maxVal+24(FP), X1
	MOVQ dst+32(FP), DX
	MOVQ countOut+40(FP), CX

	LONG $0x04fe8348 // cmpq	$0x4, %rsi
	JGE LBB1_18
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	WORD $0xc031 // xorl	%eax, %eax
LBB1_2:
	WORD $0x3949; BYTE $0xf1 // cmpq	%rsi, %r9
	JGE LBB1_17
	LONG $0x01c6f640 // testb	$0x1, %sil
	JNE LBB1_5
	WORD $0x894d; BYTE $0xc8 // movq	%r9, %r8
	LONG $0xff568d4c // leaq	-0x1(%rsi), %r10
	WORD $0x394d; BYTE $0xd1 // cmpq	%r10, %r9
	JNE LBB1_10
	JMP LBB1_17
LBB1_18:
	LONG $0x197de2c4; BYTE $0xd0 // vbroadcastsd	%xmm0, %ymm2
	LONG $0x197de2c4; BYTE $0xd9 // vbroadcastsd	%xmm1, %ymm3
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB1_19
LBB1_27:
	LONG $0x04488d4d // leaq	0x4(%r8), %r9
	LONG $0x08c08349 // addq	$0x8, %r8
	WORD $0x3949; BYTE $0xf0 // cmpq	%rsi, %r8
	WORD $0x894d; BYTE $0xc8 // movq	%r9, %r8
	JGT LBB1_2
LBB1_19:
	LONG $0x107da1c4; WORD $0xc724 // vmovupd	(%rdi,%r8,8), %ymm4
	LONG $0xebc2ddc5; BYTE $0x02 // vcmplepd	%ymm3, %ymm4, %ymm5
	LONG $0xe4c2edc5; BYTE $0x02 // vcmplepd	%ymm4, %ymm2, %ymm4
	LONG $0xe554ddc5 // vandpd	%ymm5, %ymm4, %ymm4
	LONG $0xcc507dc5 // vmovmskpd	%ymm4, %r9d
	LONG $0x01c1f641 // testb	$0x1, %r9b
	JNE LBB1_20
	LONG $0x02c1f641 // testb	$0x2, %r9b
	JNE LBB1_22
LBB1_23:
	LONG $0x04c1f641 // testb	$0x4, %r9b
	JNE LBB1_24
LBB1_25:
	LONG $0x08c1f641 // testb	$0x8, %r9b
	JE LBB1_27
	JMP LBB1_26
LBB1_20:
	LONG $0x82048944 // movl	%r8d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	LONG $0x02c1f641 // testb	$0x2, %r9b
	JE LBB1_23
LBB1_22:
	LONG $0x01508d45 // leal	0x1(%r8), %r10d
	LONG $0x82148944 // movl	%r10d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	LONG $0x04c1f641 // testb	$0x4, %r9b
	JE LBB1_25
LBB1_24:
	LONG $0x02508d45 // leal	0x2(%r8), %r10d
	LONG $0x82148944 // movl	%r10d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	LONG $0x08c1f641 // testb	$0x8, %r9b
	JE LBB1_27
LBB1_26:
	LONG $0x03488d45 // leal	0x3(%r8), %r9d
	LONG $0x820c8944 // movl	%r9d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	JMP LBB1_27
LBB1_5:
	LONG $0x107ba1c4; WORD $0xcf14 // vmovsd	(%rdi,%r9,8), %xmm2
	LONG $0xd02ef9c5 // vucomisd	%xmm0, %xmm2
	JCS LBB1_8
	LONG $0xca2ef9c5 // vucomisd	%xmm2, %xmm1
	JCS LBB1_8
	LONG $0x820c8944 // movl	%r9d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
LBB1_8:
	WORD $0x894d; BYTE $0xc8 // movq	%r9, %r8
	LONG $0x01c88349 // orq	$0x1, %r8
	LONG $0xff568d4c // leaq	-0x1(%rsi), %r10
	WORD $0x394d; BYTE $0xd1 // cmpq	%r10, %r9
	JNE LBB1_10
LBB1_17:
	WORD $0x8948; BYTE $0x01 // movq	%rax, (%rcx)
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET
LBB1_16:
	LONG $0x02c08349 // addq	$0x2, %r8
	WORD $0x394c; BYTE $0xc6 // cmpq	%r8, %rsi
	JE LBB1_17
LBB1_10:
	LONG $0x107ba1c4; WORD $0xc714 // vmovsd	(%rdi,%r8,8), %xmm2
	LONG $0xd02ef9c5 // vucomisd	%xmm0, %xmm2
	JCS LBB1_13
	LONG $0xca2ef9c5 // vucomisd	%xmm2, %xmm1
	JCS LBB1_13
	LONG $0x82048944 // movl	%r8d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
LBB1_13:
	LONG $0x107ba1c4; WORD $0xc754; BYTE $0x08 // vmovsd	0x8(%rdi,%r8,8), %xmm2
	LONG $0xd02ef9c5 // vucomisd	%xmm0, %xmm2
	JCS LBB1_16
	LONG $0xca2ef9c5 // vucomisd	%xmm2, %xmm1
	JCS LBB1_16
	LONG $0x01488d45 // leal	0x1(%r8), %r9d
	LONG $0x820c8944 // movl	%r9d, (%rdx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	JMP LBB1_16

TEXT ·gatherU32Avx2(SB), NOSPLIT, $0-32
	MOVQ src+0(FP), DI
	MOVQ indices+8(FP), SI
	MOVQ n+16(FP), DX
	MOVQ dst+24(FP), CX

	LONG $0x08fa8348 // cmpq	$0x8, %rdx
	JGE LBB3_2
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB3_8
LBB3_2:
	LONG $0xf8428d48 // leaq	-0x8(%rdx), %rax
	WORD $0x8949; BYTE $0xc1 // movq	%rax, %r9
	LONG $0x03e9c149 // shrq	$0x3, %r9
	WORD $0xff49; BYTE $0xc1 // incq	%r9
	WORD $0x8945; BYTE $0xc8 // movl	%r9d, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	LONG $0x18f88348 // cmpq	$0x18, %rax
	JCC LBB3_14
	LONG $0x0008b941; WORD $0x0000 // movl	$0x8, %r9d
	WORD $0xc031 // xorl	%eax, %eax
	WORD $0x854d; BYTE $0xc0 // testq	%r8, %r8
	JNE LBB3_6
	JMP LBB3_8
LBB3_14:
	LONG $0xfce18349 // andq	$-0x4, %r9
	WORD $0xc031 // xorl	%eax, %eax
LBB3_15:
	LONG $0x046ffec5; BYTE $0x86 // vmovdqu	(%rsi,%rax,4), %ymm0
	LONG $0xc976f5c5 // vpcmpeqd	%ymm1, %ymm1, %ymm1
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0x9075e2c4; WORD $0x8714 // vpgatherdd	%ymm1, (%rdi,%ymm0,4), %ymm2
	LONG $0x147ffec5; BYTE $0x81 // vmovdqu	%ymm2, (%rcx,%rax,4)
	LONG $0x446ffec5; WORD $0x2086 // vmovdqu	0x20(%rsi,%rax,4), %ymm0
	LONG $0xc976f5c5 // vpcmpeqd	%ymm1, %ymm1, %ymm1
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0x9075e2c4; WORD $0x8714 // vpgatherdd	%ymm1, (%rdi,%ymm0,4), %ymm2
	LONG $0x547ffec5; WORD $0x2081 // vmovdqu	%ymm2, 0x20(%rcx,%rax,4)
	LONG $0x446ffec5; WORD $0x4086 // vmovdqu	0x40(%rsi,%rax,4), %ymm0
	LONG $0xc976f5c5 // vpcmpeqd	%ymm1, %ymm1, %ymm1
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0x9075e2c4; WORD $0x8714 // vpgatherdd	%ymm1, (%rdi,%ymm0,4), %ymm2
	LONG $0x547ffec5; WORD $0x4081 // vmovdqu	%ymm2, 0x40(%rcx,%rax,4)
	LONG $0x446ffec5; WORD $0x6086 // vmovdqu	0x60(%rsi,%rax,4), %ymm0
	LONG $0xc976f5c5 // vpcmpeqd	%ymm1, %ymm1, %ymm1
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0x9075e2c4; WORD $0x8714 // vpgatherdd	%ymm1, (%rdi,%ymm0,4), %ymm2
	LONG $0x547ffec5; WORD $0x6081 // vmovdqu	%ymm2, 0x60(%rcx,%rax,4)
	LONG $0x20c08348 // addq	$0x20, %rax
	LONG $0xfcc18349 // addq	$-0x4, %r9
	JNE LBB3_15
	LONG $0x08488d4c // leaq	0x8(%rax), %r9
	WORD $0x854d; BYTE $0xc0 // testq	%r8, %r8
	JE LBB3_8
LBB3_6:
	LONG $0x046ffec5; BYTE $0x86 // vmovdqu	(%rsi,%rax,4), %ymm0
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	LONG $0xd276edc5 // vpcmpeqd	%ymm2, %ymm2, %ymm2
	LONG $0x906de2c4; WORD $0x870c // vpgatherdd	%ymm2, (%rdi,%ymm0,4), %ymm1
	LONG $0x0c7ffec5; BYTE $0x81 // vmovdqu	%ymm1, (%rcx,%rax,4)
	WORD $0x894c; BYTE $0xc8 // movq	%r9, %rax
	LONG $0x08c18349 // addq	$0x8, %r9
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB3_6
	LONG $0xf8c18349 // addq	$-0x8, %r9
	WORD $0x894c; BYTE $0xc8 // movq	%r9, %rax
LBB3_8:
	WORD $0x8949; BYTE $0xc0 // movq	%rax, %r8
	WORD $0x2949; BYTE $0xd0 // subq	%rdx, %r8
	JGE LBB3_13
	WORD $0x8941; BYTE $0xd1 // movl	%edx, %r9d
	WORD $0x2941; BYTE $0xc1 // subl	%eax, %r9d
	LONG $0x03e18341 // andl	$0x3, %r9d
	JE LBB3_11
LBB3_10:
	LONG $0x8614634c // movslq	(%rsi,%rax,4), %r10
	LONG $0x97148b46 // movl	(%rdi,%r10,4), %r10d
	LONG $0x81148944 // movl	%r10d, (%rcx,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff49; BYTE $0xc9 // decq	%r9
	JNE LBB3_10
LBB3_11:
	LONG $0xfcf88349 // cmpq	$-0x4, %r8
	JHI LBB3_13
LBB3_12:
	LONG $0x8604634c // movslq	(%rsi,%rax,4), %r8
	LONG $0x87048b46 // movl	(%rdi,%r8,4), %r8d
	LONG $0x81048944 // movl	%r8d, (%rcx,%rax,4)
	LONG $0x8644634c; BYTE $0x04 // movslq	0x4(%rsi,%rax,4), %r8
	LONG $0x87048b46 // movl	(%rdi,%r8,4), %r8d
	LONG $0x81448944; BYTE $0x04 // movl	%r8d, 0x4(%rcx,%rax,4)
	LONG $0x8644634c; BYTE $0x08 // movslq	0x8(%rsi,%rax,4), %r8
	LONG $0x87048b46 // movl	(%rdi,%r8,4), %r8d
	LONG $0x81448944; BYTE $0x08 // movl	%r8d, 0x8(%rcx,%rax,4)
	LONG $0x8644634c; BYTE $0x0c // movslq	0xc(%rsi,%rax,4), %r8
	LONG $0x87048b46 // movl	(%rdi,%r8,4), %r8d
	LONG $0x81448944; BYTE $0x0c // movl	%r8d, 0xc(%rcx,%rax,4)
	LONG $0x04c08348 // addq	$0x4, %rax
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JNE LBB3_12
LBB3_13:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

