// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func countRangeF64Sve2(values unsafe.Pointer, n int64, minVal float64, maxVal float64) int64

//go:noescape
func filterRangeF64IndicesSve2(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer) int64

//go:noescape
func filterRangeF64Sve2(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer)

//go:noescape
func filterRangeF64Sve2Simple(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer)

//go:noescape
func gatherU32Sve2(src unsafe.Pointer, indices unsafe.Pointer, n int64, dst unsafe.Pointer)

