// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func countRangeF64Neon(values unsafe.Pointer, n int64, minVal float64, maxVal float64, countOut unsafe.Pointer)

//go:noescape
func filterRangeF64IndicesNeon(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer, countOut unsafe.Pointer)

//go:noescape
func filterRangeF64Neon(values unsafe.Pointer, n int64, minVal float64, maxVal float64, dst unsafe.Pointer)

//go:noescape
func gatherU32Neon(src unsafe.Pointer, indices unsafe.Pointer, n int64, dst unsafe.Pointer)

