// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func dotProductAvx2(a unsafe.Pointer, b unsafe.Pointer, n int64, res unsafe.Pointer)

//go:noescape
func pqAdcLookupAvx2(table unsafe.Pointer, codes unsafe.Pointer, m int64, result unsafe.Pointer, offsets_ptr unsafe.Pointer)

//go:noescape
func scaleAvx2(a unsafe.Pointer, n int64, scalar unsafe.Pointer)

//go:noescape
func squaredL2Avx2(vec1 unsafe.Pointer, vec2 unsafe.Pointer, n int64, result unsafe.Pointer)

