// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·dotProductAvx2(SB), NOSPLIT, $0-32
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX
	MOVQ res+24(FP), CX

	LONG $0x1f428d4c // leaq	0x1f(%rdx), %r8
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	LONG $0xc2490f4c // cmovnsq	%rdx, %r8
	WORD $0x894d; BYTE $0xc1 // movq	%r8, %r9
	LONG $0xe0e18349 // andq	$-0x20, %r9
	WORD $0x8948; BYTE $0xd0 // movq	%rdx, %rax
	WORD $0x294c; BYTE $0xc8 // subq	%r9, %rax
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	LONG $0x20fa8348 // cmpq	$0x20, %rdx
	JLT LBB0_4
	LONG $0x05f8c149 // sarq	$0x5, %r8
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xd257e8c5 // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
LBB0_2:
	QUAD $0x0001000f8c180f42; BYTE $0x00 // prefetcht0	0x100(%rdi,%r9)
	QUAD $0x0001000e8c180f42; BYTE $0x00 // prefetcht0	0x100(%rsi,%r9)
	LONG $0x107ca1c4; WORD $0x0f24 // vmovups	(%rdi,%r9), %ymm4
	LONG $0x107ca1c4; WORD $0x0f6c; BYTE $0x20 // vmovups	0x20(%rdi,%r9), %ymm5
	LONG $0x107ca1c4; WORD $0x0f74; BYTE $0x40 // vmovups	0x40(%rdi,%r9), %ymm6
	LONG $0x107ca1c4; WORD $0x0f7c; BYTE $0x60 // vmovups	0x60(%rdi,%r9), %ymm7
	LONG $0xb85da2c4; WORD $0x0e04 // vfmadd231ps	(%rsi,%r9), %ymm4, %ymm0 # ymm0 = (ymm4 * mem) + ymm0
	LONG $0xb855a2c4; WORD $0x0e4c; BYTE $0x20 // vfmadd231ps	0x20(%rsi,%r9), %ymm5, %ymm1 # ymm1 = (ymm5 * mem) + ymm1
	LONG $0xb84da2c4; WORD $0x0e54; BYTE $0x40 // vfmadd231ps	0x40(%rsi,%r9), %ymm6, %ymm2 # ymm2 = (ymm6 * mem) + ymm2
	LONG $0xb845a2c4; WORD $0x0e5c; BYTE $0x60 // vfmadd231ps	0x60(%rsi,%r9), %ymm7, %ymm3 # ymm3 = (ymm7 * mem) + ymm3
	LONG $0x80e98349 // subq	$-0x80, %r9
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB0_2
	LONG $0xc058f4c5 // vaddps	%ymm0, %ymm1, %ymm0
	LONG $0xca58e4c5 // vaddps	%ymm2, %ymm3, %ymm1
	LONG $0xc058f4c5 // vaddps	%ymm0, %ymm1, %ymm0
LBB0_4:
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JLE LBB0_7
	WORD $0x8949; BYTE $0xd0 // movq	%rdx, %r8
	WORD $0x2949; BYTE $0xc0 // subq	%rax, %r8
LBB0_6:
	LONG $0x107aa1c4; WORD $0x870c // vmovss	(%rdi,%r8,4), %xmm1
	LONG $0xb971a2c4; WORD $0x8604 // vfmadd231ss	(%rsi,%r8,4), %xmm1, %xmm0 # xmm0 = (xmm1 * mem) + xmm0
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x3949; BYTE $0xd0 // cmpq	%rdx, %r8
	JLT LBB0_6
LBB0_7:
	LONG $0x0111fac5 // vmovss	%xmm0, (%rcx)
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·pqAdcLookupAvx2(SB), NOSPLIT, $0-40
	MOVQ table+0(FP), DI
	MOVQ codes+8(FP), SI
	MOVQ m+16(FP), DX
	MOVQ result+24(FP), CX
	MOVQ offsets_ptr+32(FP), R8

	LONG $0x08fa8348 // cmpq	$0x8, %rdx
	JGE LBB2_2
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0xc031 // xorl	%eax, %eax
	JMP LBB2_10
LBB2_2:
	LONG $0x6f7ec1c4; BYTE $0x00 // vmovdqu	(%r8), %ymm0
	LONG $0xf8428d48 // leaq	-0x8(%rdx), %rax
	WORD $0x8949; BYTE $0xc2 // movq	%rax, %r10
	LONG $0x03eac149 // shrq	$0x3, %r10
	WORD $0xff49; BYTE $0xc2 // incq	%r10
	WORD $0x8945; BYTE $0xd0 // movl	%r10d, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	LONG $0x18f88348 // cmpq	$0x18, %rax
	JAE LBB2_4
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	JMP LBB2_6
LBB2_4:
	LONG $0xfce28349 // andq	$-0x4, %r10
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
LBB2_5:
	LONG $0x317da2c4; WORD $0x0e14 // vpmovzxbd	(%rsi,%r9), %ymm2
	LONG $0xd2fefdc5 // vpaddd	%ymm2, %ymm0, %ymm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xe476ddc5 // vpcmpeqd	%ymm4, %ymm4, %ymm4
	LONG $0x925de2c4; WORD $0x971c // vgatherdps	%ymm4, (%rdi,%ymm2,4), %ymm3
	LONG $0xcb58f4c5 // vaddps	%ymm3, %ymm1, %ymm1
	LONG $0x317da2c4; WORD $0x0e54; BYTE $0x08 // vpmovzxbd	0x8(%rsi,%r9), %ymm2
	LONG $0xd2fefdc5 // vpaddd	%ymm2, %ymm0, %ymm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xe476ddc5 // vpcmpeqd	%ymm4, %ymm4, %ymm4
	QUAD $0x2000979c925de2c4; WORD $0x0000 // vgatherdps	%ymm4, 0x2000(%rdi,%ymm2,4), %ymm3
	LONG $0x317da2c4; WORD $0x0e54; BYTE $0x10 // vpmovzxbd	0x10(%rsi,%r9), %ymm2
	LONG $0xcb58f4c5 // vaddps	%ymm3, %ymm1, %ymm1
	LONG $0xd2fefdc5 // vpaddd	%ymm2, %ymm0, %ymm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xe476ddc5 // vpcmpeqd	%ymm4, %ymm4, %ymm4
	QUAD $0x4000979c925de2c4; WORD $0x0000 // vgatherdps	%ymm4, 0x4000(%rdi,%ymm2,4), %ymm3
	LONG $0xcb58f4c5 // vaddps	%ymm3, %ymm1, %ymm1
	LONG $0x317da2c4; WORD $0x0e54; BYTE $0x18 // vpmovzxbd	0x18(%rsi,%r9), %ymm2
	LONG $0xd2fefdc5 // vpaddd	%ymm2, %ymm0, %ymm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
	LONG $0xe476ddc5 // vpcmpeqd	%ymm4, %ymm4, %ymm4
	QUAD $0x6000979c925de2c4; WORD $0x0000 // vgatherdps	%ymm4, 0x6000(%rdi,%ymm2,4), %ymm3
	LONG $0xcb58f4c5 // vaddps	%ymm3, %ymm1, %ymm1
	LONG $0x00c78148; WORD $0x0080; BYTE $0x00 // addq	$0x8000, %rdi           # imm = 0x8000
	LONG $0x20c18349 // addq	$0x20, %r9
	LONG $0xfcc28349 // addq	$-0x4, %r10
	JNE LBB2_5
LBB2_6:
	LONG $0xf8e08348 // andq	$-0x8, %rax
	WORD $0x854d; BYTE $0xc0 // testq	%r8, %r8
	JE LBB2_9
	WORD $0x0149; BYTE $0xf1 // addq	%rsi, %r9
	WORD $0x3145; BYTE $0xd2 // xorl	%r10d, %r10d
LBB2_8:
	LONG $0x317d82c4; WORD $0xd114 // vpmovzxbd	(%r9,%r10,8), %ymm2
	LONG $0xd2fefdc5 // vpaddd	%ymm2, %ymm0, %ymm2
	LONG $0xdb76e5c5 // vpcmpeqd	%ymm3, %ymm3, %ymm3
	LONG $0xe457d8c5 // vxorps	%xmm4, %xmm4, %xmm4
	LONG $0x9265e2c4; WORD $0x9724 // vgatherdps	%ymm3, (%rdi,%ymm2,4), %ymm4
	LONG $0xcc58f4c5 // vaddps	%ymm4, %ymm1, %ymm1
	LONG $0x00c78148; WORD $0x0020; BYTE $0x00 // addq	$0x2000, %rdi           # imm = 0x2000
	WORD $0xff49; BYTE $0xc2 // incq	%r10
	WORD $0x394d; BYTE $0xd0 // cmpq	%r10, %r8
	JNE LBB2_8
LBB2_9:
	LONG $0x08c08348 // addq	$0x8, %rax
LBB2_10:
	LONG $0x197de3c4; WORD $0x01c8 // vextractf128	$0x1, %ymm1, %xmm0
	LONG $0xc058f0c5 // vaddps	%xmm0, %xmm1, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	WORD $0x8949; BYTE $0xc0 // movq	%rax, %r8
	WORD $0x2949; BYTE $0xd0 // subq	%rdx, %r8
	JGE LBB2_16
	WORD $0x8941; BYTE $0xd1 // movl	%edx, %r9d
	WORD $0x2941; BYTE $0xc1 // subl	%eax, %r9d
	LONG $0x03e18341 // andl	$0x3, %r9d
	JE LBB2_13
LBB2_12:
	LONG $0x14b60f44; BYTE $0x06 // movzbl	(%rsi,%rax), %r10d
	LONG $0x587aa1c4; WORD $0x9704 // vaddss	(%rdi,%r10,4), %xmm0, %xmm0
	LONG $0x00c78148; WORD $0x0004; BYTE $0x00 // addq	$0x400, %rdi            # imm = 0x400
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff49; BYTE $0xc9 // decq	%r9
	JNE LBB2_12
LBB2_13:
	LONG $0xfcf88349 // cmpq	$-0x4, %r8
	JHI LBB2_16
	LONG $0x00c78148; WORD $0x0008; BYTE $0x00 // addq	$0x800, %rdi            # imm = 0x800
LBB2_15:
	LONG $0x04b60f44; BYTE $0x06 // movzbl	(%rsi,%rax), %r8d
	QUAD $0xf8008784587aa1c4; WORD $0xffff // vaddss	-0x800(%rdi,%r8,4), %xmm0, %xmm0
	LONG $0x44b60f44; WORD $0x0106 // movzbl	0x1(%rsi,%rax), %r8d
	QUAD $0xfc008784587aa1c4; WORD $0xffff // vaddss	-0x400(%rdi,%r8,4), %xmm0, %xmm0
	LONG $0x44b60f44; WORD $0x0206 // movzbl	0x2(%rsi,%rax), %r8d
	LONG $0x587aa1c4; WORD $0x8704 // vaddss	(%rdi,%r8,4), %xmm0, %xmm0
	LONG $0x44b60f44; WORD $0x0306 // movzbl	0x3(%rsi,%rax), %r8d
	QUAD $0x04008784587aa1c4; WORD $0x0000 // vaddss	0x400(%rdi,%r8,4), %xmm0, %xmm0
	LONG $0x04c08348 // addq	$0x4, %rax
	LONG $0x00c78148; WORD $0x0010; BYTE $0x00 // addq	$0x1000, %rdi           # imm = 0x1000
	WORD $0x3948; BYTE $0xc2 // cmpq	%rax, %rdx
	JNE LBB2_15
LBB2_16:
	LONG $0x0111fac5 // vmovss	%xmm0, (%rcx)
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·scaleAvx2(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), DI
	MOVQ n+8(FP), SI
	MOVQ scalar+16(FP), DX

	WORD $0x8548; BYTE $0xf6 // testq	%rsi, %rsi
	JLE LBB3_9
	LONG $0x187de2c4; BYTE $0x02 // vbroadcastss	(%rdx), %ymm0
	LONG $0x20fe8348 // cmpq	$0x20, %rsi
	JLO LBB3_4
	WORD $0x8948; BYTE $0xf0 // movq	%rsi, %rax
	LONG $0x05e8c148 // shrq	$0x5, %rax
	WORD $0x8948; BYTE $0xf9 // movq	%rdi, %rcx
LBB3_3:
	LONG $0x0089180f; WORD $0x0001; BYTE $0x00 // prefetcht0	0x100(%rcx)
	LONG $0x0959fcc5 // vmulps	(%rcx), %ymm0, %ymm1
	LONG $0x5159fcc5; BYTE $0x20 // vmulps	0x20(%rcx), %ymm0, %ymm2
	LONG $0x5959fcc5; BYTE $0x40 // vmulps	0x40(%rcx), %ymm0, %ymm3
	LONG $0x6159fcc5; BYTE $0x60 // vmulps	0x60(%rcx), %ymm0, %ymm4
	LONG $0x0911fcc5 // vmovups	%ymm1, (%rcx)
	LONG $0x5111fcc5; BYTE $0x20 // vmovups	%ymm2, 0x20(%rcx)
	LONG $0x5911fcc5; BYTE $0x40 // vmovups	%ymm3, 0x40(%rcx)
	LONG $0x6111fcc5; BYTE $0x60 // vmovups	%ymm4, 0x60(%rcx)
	LONG $0x80e98348 // subq	$-0x80, %rcx
	WORD $0xff48; BYTE $0xc8 // decq	%rax
	JNE LBB3_3
LBB3_4:
	QUAD $0xffffffffffe0b848; WORD $0x7fff // movabsq	$0x7fffffffffffffe0, %rax # imm = 0x7FFFFFFFFFFFFFE0
	WORD $0x2148; BYTE $0xf0 // andq	%rsi, %rax
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	WORD $0x2948; BYTE $0xf1 // subq	%rsi, %rcx
	JGE LBB3_9
	WORD $0x8948; BYTE $0xf2 // movq	%rsi, %rdx
	LONG $0x03e28348 // andq	$0x3, %rdx
	JE LBB3_7
LBB3_6:
	LONG $0x0c59fac5; BYTE $0x87 // vmulss	(%rdi,%rax,4), %xmm0, %xmm1
	LONG $0x0c11fac5; BYTE $0x87 // vmovss	%xmm1, (%rdi,%rax,4)
	WORD $0xff48; BYTE $0xc0 // incq	%rax
	WORD $0xff48; BYTE $0xca // decq	%rdx
	JNE LBB3_6
LBB3_7:
	LONG $0xfcf98348 // cmpq	$-0x4, %rcx
	JHI LBB3_9
LBB3_8:
	LONG $0x0c59fac5; BYTE $0x87 // vmulss	(%rdi,%rax,4), %xmm0, %xmm1
	LONG $0x0c11fac5; BYTE $0x87 // vmovss	%xmm1, (%rdi,%rax,4)
	LONG $0x4c59fac5; WORD $0x0487 // vmulss	0x4(%rdi,%rax,4), %xmm0, %xmm1
	LONG $0x4c11fac5; WORD $0x0487 // vmovss	%xmm1, 0x4(%rdi,%rax,4)
	LONG $0x4c59fac5; WORD $0x0887 // vmulss	0x8(%rdi,%rax,4), %xmm0, %xmm1
	LONG $0x4c11fac5; WORD $0x0887 // vmovss	%xmm1, 0x8(%rdi,%rax,4)
	LONG $0x4c59fac5; WORD $0x0c87 // vmulss	0xc(%rdi,%rax,4), %xmm0, %xmm1
	LONG $0x4c11fac5; WORD $0x0c87 // vmovss	%xmm1, 0xc(%rdi,%rax,4)
	LONG $0x04c08348 // addq	$0x4, %rax
	WORD $0x3948; BYTE $0xf0 // cmpq	%rsi, %rax
	JLT LBB3_8
LBB3_9:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

TEXT ·squaredL2Avx2(SB), NOSPLIT, $0-32
	MOVQ vec1+0(FP), DI
	MOVQ vec2+8(FP), SI
	MOVQ n+16(FP), DX
	MOVQ result+24(FP), CX

	LONG $0x1f428d4c // leaq	0x1f(%rdx), %r8
	WORD $0x8548; BYTE $0xd2 // testq	%rdx, %rdx
	LONG $0xc2490f4c // cmovnsq	%rdx, %r8
	WORD $0x894d; BYTE $0xc1 // movq	%r8, %r9
	LONG $0xe0e18349 // andq	$-0x20, %r9
	WORD $0x8948; BYTE $0xd0 // movq	%rdx, %rax
	WORD $0x294c; BYTE $0xc8 // subq	%r9, %rax
	LONG $0xc057f8c5 // vxorps	%xmm0, %xmm0, %xmm0
	LONG $0x20fa8348 // cmpq	$0x20, %rdx
	JLT LBB1_4
	LONG $0x05f8c149 // sarq	$0x5, %r8
	WORD $0x3145; BYTE $0xc9 // xorl	%r9d, %r9d
	LONG $0xc957f0c5 // vxorps	%xmm1, %xmm1, %xmm1
	LONG $0xd257e8c5 // vxorps	%xmm2, %xmm2, %xmm2
	LONG $0xdb57e0c5 // vxorps	%xmm3, %xmm3, %xmm3
LBB1_2:
	QUAD $0x0001000f8c180f42; BYTE $0x00 // prefetcht0	0x100(%rdi,%r9)
	QUAD $0x0001000e8c180f42; BYTE $0x00 // prefetcht0	0x100(%rsi,%r9)
	LONG $0x107ca1c4; WORD $0x0f24 // vmovups	(%rdi,%r9), %ymm4
	LONG $0x107ca1c4; WORD $0x0f6c; BYTE $0x20 // vmovups	0x20(%rdi,%r9), %ymm5
	LONG $0x107ca1c4; WORD $0x0f74; BYTE $0x40 // vmovups	0x40(%rdi,%r9), %ymm6
	LONG $0x107ca1c4; WORD $0x0f7c; BYTE $0x60 // vmovups	0x60(%rdi,%r9), %ymm7
	LONG $0x5c5ca1c4; WORD $0x0e24 // vsubps	(%rsi,%r9), %ymm4, %ymm4
	LONG $0x5c54a1c4; WORD $0x0e6c; BYTE $0x20 // vsubps	0x20(%rsi,%r9), %ymm5, %ymm5
	LONG $0x5c4ca1c4; WORD $0x0e74; BYTE $0x40 // vsubps	0x40(%rsi,%r9), %ymm6, %ymm6
	LONG $0x5c44a1c4; WORD $0x0e7c; BYTE $0x60 // vsubps	0x60(%rsi,%r9), %ymm7, %ymm7
	LONG $0xb85de2c4; BYTE $0xc4 // vfmadd231ps	%ymm4, %ymm4, %ymm0 # ymm0 = (ymm4 * ymm4) + ymm0
	LONG $0xb855e2c4; BYTE $0xcd // vfmadd231ps	%ymm5, %ymm5, %ymm1 # ymm1 = (ymm5 * ymm5) + ymm1
	LONG $0xb84de2c4; BYTE $0xd6 // vfmadd231ps	%ymm6, %ymm6, %ymm2 # ymm2 = (ymm6 * ymm6) + ymm2
	LONG $0xb845e2c4; BYTE $0xdf // vfmadd231ps	%ymm7, %ymm7, %ymm3 # ymm3 = (ymm7 * ymm7) + ymm3
	LONG $0x80e98349 // subq	$-0x80, %r9
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB1_2
	LONG $0xc058f4c5 // vaddps	%ymm0, %ymm1, %ymm0
	LONG $0xca58e4c5 // vaddps	%ymm2, %ymm3, %ymm1
	LONG $0xc058f4c5 // vaddps	%ymm0, %ymm1, %ymm0
LBB1_4:
	LONG $0x197de3c4; WORD $0x01c1 // vextractf128	$0x1, %ymm0, %xmm1
	LONG $0xc158f8c5 // vaddps	%xmm1, %xmm0, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	LONG $0xc07cfbc5 // vhaddps	%xmm0, %xmm0, %xmm0
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JLE LBB1_7
	WORD $0x8949; BYTE $0xd0 // movq	%rdx, %r8
	WORD $0x2949; BYTE $0xc0 // subq	%rax, %r8
LBB1_6:
	LONG $0x107aa1c4; WORD $0x870c // vmovss	(%rdi,%r8,4), %xmm1
	LONG $0x5c72a1c4; WORD $0x860c // vsubss	(%rsi,%r8,4), %xmm1, %xmm1
	LONG $0xb971e2c4; BYTE $0xc1 // vfmadd231ss	%xmm1, %xmm1, %xmm0 # xmm0 = (xmm1 * xmm1) + xmm0
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x3949; BYTE $0xd0 // cmpq	%rdx, %r8
	JLT LBB1_6
LBB1_7:
	LONG $0x0111fac5 // vmovss	%xmm0, (%rcx)
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	RET

