// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func int4L2DistanceAvx2(query unsafe.Pointer, code unsafe.Pointer, dim int64, minVal unsafe.Pointer, diff unsafe.Pointer, out unsafe.Pointer)

//go:noescape
func int4L2DistanceBatchAvx2(query unsafe.Pointer, codes unsafe.Pointer, dim int64, n int64, minVal unsafe.Pointer, diff unsafe.Pointer, out unsafe.Pointer)

//go:noescape
func int4L2DistancePrecomputedAvx2(query unsafe.Pointer, code unsafe.Pointer, dim int64, lookupTable unsafe.Pointer, out unsafe.Pointer)

