// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func hammingAvx512(a unsafe.Pointer, b unsafe.Pointer, n int64) int64

//go:noescape
func popcountAvx512(a unsafe.Pointer, n int64) int64

