// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·hammingAvx512(SB), NOSPLIT, $0-32
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX

	LONG $0x40fa8348 // cmpq	$0x40, %rdx
	JGE LBB1_2
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0xc931 // xorl	%ecx, %ecx
	JMP LBB1_10
LBB1_2:
	LONG $0xc04a8d48 // leaq	-0x40(%rdx), %rcx
	WORD $0x8949; BYTE $0xc9 // movq	%rcx, %r9
	LONG $0x06e9c149 // shrq	$0x6, %r9
	WORD $0xff49; BYTE $0xc1 // incq	%r9
	WORD $0x8944; BYTE $0xc8 // movl	%r9d, %eax
	WORD $0xe083; BYTE $0x03 // andl	$0x3, %eax
	LONG $0xc0f98148; WORD $0x0000; BYTE $0x00 // cmpq	$0xc0, %rcx
	JCC LBB1_4
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
	JMP LBB1_6
LBB1_4:
	LONG $0xfce18349 // andq	$-0x4, %r9
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
LBB1_5:
	LONG $0x48feb162; WORD $0x0c6f; BYTE $0x06 // vmovdqu64	(%rsi,%r8), %zmm1
	QUAD $0x0106546f48feb162 // vmovdqu64	0x40(%rsi,%r8), %zmm2
	QUAD $0x02065c6f48feb162 // vmovdqu64	0x80(%rsi,%r8), %zmm3
	QUAD $0x0306646f48feb162 // vmovdqu64	0xc0(%rsi,%r8), %zmm4
	LONG $0x48f5b162; WORD $0x0cef; BYTE $0x07 // vpxorq	(%rdi,%r8), %zmm1, %zmm1
	LONG $0x48fdf262; WORD $0xc955 // vpopcntq	%zmm1, %zmm1
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	QUAD $0x01074cef48edb162 // vpxorq	0x40(%rdi,%r8), %zmm2, %zmm1
	LONG $0x48fdf262; WORD $0xc955 // vpopcntq	%zmm1, %zmm1
	QUAD $0x020754ef48e5b162 // vpxorq	0x80(%rdi,%r8), %zmm3, %zmm2
	LONG $0x48fdf262; WORD $0xd255 // vpopcntq	%zmm2, %zmm2
	LONG $0x48edf162; WORD $0xc9d4 // vpaddq	%zmm1, %zmm2, %zmm1
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	QUAD $0x03074cef48ddb162 // vpxorq	0xc0(%rdi,%r8), %zmm4, %zmm1
	LONG $0x48fdf262; WORD $0xc955 // vpopcntq	%zmm1, %zmm1
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	LONG $0x00c08149; WORD $0x0001; BYTE $0x00 // addq	$0x100, %r8             # imm = 0x100
	LONG $0xfcc18349 // addq	$-0x4, %r9
	JNE LBB1_5
LBB1_6:
	LONG $0xc0e18348 // andq	$-0x40, %rcx
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JE LBB1_9
	LONG $0x060c8d4e // leaq	(%rsi,%r8), %r9
	WORD $0x0149; BYTE $0xf8 // addq	%rdi, %r8
	WORD $0xe0c1; BYTE $0x06 // shll	$0x6, %eax
	WORD $0x3145; BYTE $0xd2 // xorl	%r10d, %r10d
LBB1_8:
	LONG $0x48fe9162; WORD $0x0c6f; BYTE $0x11 // vmovdqu64	(%r9,%r10), %zmm1
	LONG $0x48f59162; WORD $0x0cef; BYTE $0x10 // vpxorq	(%r8,%r10), %zmm1, %zmm1
	LONG $0x48fdf262; WORD $0xc955 // vpopcntq	%zmm1, %zmm1
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	LONG $0x40c28349 // addq	$0x40, %r10
	WORD $0x394c; BYTE $0xd0 // cmpq	%r10, %rax
	JNE LBB1_8
LBB1_9:
	LONG $0x40c18348 // addq	$0x40, %rcx
LBB1_10:
	LONG $0x48fdf362; WORD $0xc13b; BYTE $0x01 // vextracti64x4	$0x1, %zmm0, %ymm1
	LONG $0x48fdf162; WORD $0xc1d4 // vpaddq	%zmm1, %zmm0, %zmm0
	LONG $0x397de3c4; WORD $0x01c1 // vextracti128	$0x1, %ymm0, %xmm1
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0xc870f9c5; BYTE $0xee // vpshufd	$0xee, %xmm0, %xmm1     # xmm1 = xmm0[2,3,2,3]
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	%xmm0, %rax
	WORD $0x3948; BYTE $0xca // cmpq	%rcx, %rdx
	JLE LBB1_16
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc8 // subl	%ecx, %r8d
	LONG $0x01c0f641 // testb	$0x1, %r8b
	JNE LBB1_13
	WORD $0x8949; BYTE $0xc8 // movq	%rcx, %r8
	LONG $0xff4a8d4c // leaq	-0x1(%rdx), %r9
	WORD $0x394c; BYTE $0xc9 // cmpq	%r9, %rcx
	JNE LBB1_15
	JMP LBB1_16
LBB1_13:
	LONG $0x04b60f44; BYTE $0x0e // movzbl	(%rsi,%rcx), %r8d
	LONG $0x0f043244 // xorb	(%rdi,%rcx), %r8b
	LONG $0xc0b60f45 // movzbl	%r8b, %r8d
	LONG $0xb80f45f3; BYTE $0xc0 // popcntl	%r8d, %r8d
	WORD $0x014c; BYTE $0xc0 // addq	%r8, %rax
	LONG $0x01418d4c // leaq	0x1(%rcx), %r8
	LONG $0xff4a8d4c // leaq	-0x1(%rdx), %r9
	WORD $0x394c; BYTE $0xc9 // cmpq	%r9, %rcx
	JE LBB1_16
LBB1_15:
	LONG $0x0cb60f42; BYTE $0x06 // movzbl	(%rsi,%r8), %ecx
	LONG $0x4cb60f46; WORD $0x0106 // movzbl	0x1(%rsi,%r8), %r9d
	LONG $0x070c3242 // xorb	(%rdi,%r8), %cl
	WORD $0xb60f; BYTE $0xc9 // movzbl	%cl, %ecx
	LONG $0xc9b80ff3 // popcntl	%ecx, %ecx
	WORD $0x0148; BYTE $0xc1 // addq	%rax, %rcx
	LONG $0x074c3246; BYTE $0x01 // xorb	0x1(%rdi,%r8), %r9b
	LONG $0xc1b60f41 // movzbl	%r9b, %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	WORD $0x0148; BYTE $0xc8 // addq	%rcx, %rax
	LONG $0x02c08349 // addq	$0x2, %r8
	WORD $0x394c; BYTE $0xc2 // cmpq	%r8, %rdx
	JNE LBB1_15
LBB1_16:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	MOVQ AX, ret+24(FP)
	RET

TEXT ·popcountAvx512(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), DI
	MOVQ n+8(FP), SI

	LONG $0x40fe8348 // cmpq	$0x40, %rsi
	JGE LBB0_2
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0xc931 // xorl	%ecx, %ecx
	JMP LBB0_10
LBB0_2:
	LONG $0xc04e8d48 // leaq	-0x40(%rsi), %rcx
	WORD $0x8949; BYTE $0xc8 // movq	%rcx, %r8
	LONG $0x06e8c149 // shrq	$0x6, %r8
	WORD $0xff49; BYTE $0xc0 // incq	%r8
	WORD $0x8944; BYTE $0xc0 // movl	%r8d, %eax
	WORD $0xe083; BYTE $0x03 // andl	$0x3, %eax
	LONG $0xc0f98148; WORD $0x0000; BYTE $0x00 // cmpq	$0xc0, %rcx
	JCC LBB0_4
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0xd231 // xorl	%edx, %edx
	JMP LBB0_6
LBB0_4:
	LONG $0xfce08349 // andq	$-0x4, %r8
	LONG $0xc0eff9c5 // vpxor	%xmm0, %xmm0, %xmm0
	WORD $0xd231 // xorl	%edx, %edx
LBB0_5:
	LONG $0x48fdf262; WORD $0x0c55; BYTE $0x17 // vpopcntq	(%rdi,%rdx), %zmm1
	QUAD $0x0117545548fdf262 // vpopcntq	0x40(%rdi,%rdx), %zmm2
	QUAD $0x02175c5548fdf262 // vpopcntq	0x80(%rdi,%rdx), %zmm3
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	LONG $0x48e5f162; WORD $0xcad4 // vpaddq	%zmm2, %zmm3, %zmm1
	QUAD $0x0317545548fdf262 // vpopcntq	0xc0(%rdi,%rdx), %zmm2
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	LONG $0x48edf162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm2, %zmm0
	LONG $0x00c28148; WORD $0x0001; BYTE $0x00 // addq	$0x100, %rdx            # imm = 0x100
	LONG $0xfcc08349 // addq	$-0x4, %r8
	JNE LBB0_5
LBB0_6:
	LONG $0xc0e18348 // andq	$-0x40, %rcx
	WORD $0x8548; BYTE $0xc0 // testq	%rax, %rax
	JE LBB0_9
	WORD $0x0148; BYTE $0xfa // addq	%rdi, %rdx
	WORD $0xe0c1; BYTE $0x06 // shll	$0x6, %eax
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
LBB0_8:
	LONG $0x48fdb262; WORD $0x0c55; BYTE $0x02 // vpopcntq	(%rdx,%r8), %zmm1
	LONG $0x48f5f162; WORD $0xc0d4 // vpaddq	%zmm0, %zmm1, %zmm0
	LONG $0x40c08349 // addq	$0x40, %r8
	WORD $0x394c; BYTE $0xc0 // cmpq	%r8, %rax
	JNE LBB0_8
LBB0_9:
	LONG $0x40c18348 // addq	$0x40, %rcx
LBB0_10:
	LONG $0x48fdf362; WORD $0xc13b; BYTE $0x01 // vextracti64x4	$0x1, %zmm0, %ymm1
	LONG $0x48fdf162; WORD $0xc1d4 // vpaddq	%zmm1, %zmm0, %zmm0
	LONG $0x397de3c4; WORD $0x01c1 // vextracti128	$0x1, %ymm0, %xmm1
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0xc870f9c5; BYTE $0xee // vpshufd	$0xee, %xmm0, %xmm1     # xmm1 = xmm0[2,3,2,3]
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	%xmm0, %rax
	WORD $0x8948; BYTE $0xca // movq	%rcx, %rdx
	WORD $0x2948; BYTE $0xf2 // subq	%rsi, %rdx
	JGE LBB0_15
	WORD $0x8941; BYTE $0xf0 // movl	%esi, %r8d
	WORD $0x2941; BYTE $0xc8 // subl	%ecx, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	JE LBB0_13
LBB0_12:
	LONG $0x0cb60f44; BYTE $0x0f // movzbl	(%rdi,%rcx), %r9d
	LONG $0xb80f45f3; BYTE $0xc9 // popcntl	%r9d, %r9d
	WORD $0x014c; BYTE $0xc8 // addq	%r9, %rax
	WORD $0xff48; BYTE $0xc1 // incq	%rcx
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB0_12
LBB0_13:
	LONG $0xfcfa8348 // cmpq	$-0x4, %rdx
	JHI LBB0_15
LBB0_14:
	LONG $0x0f14b60f // movzbl	(%rdi,%rcx), %edx
	LONG $0xd2b80ff3 // popcntl	%edx, %edx
	WORD $0x0148; BYTE $0xc2 // addq	%rax, %rdx
	LONG $0x0f44b60f; BYTE $0x01 // movzbl	0x1(%rdi,%rcx), %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	LONG $0x44b60f44; WORD $0x020f // movzbl	0x2(%rdi,%rcx), %r8d
	LONG $0xb80f45f3; BYTE $0xc0 // popcntl	%r8d, %r8d
	WORD $0x0149; BYTE $0xc0 // addq	%rax, %r8
	WORD $0x0149; BYTE $0xd0 // addq	%rdx, %r8
	LONG $0x0f44b60f; BYTE $0x03 // movzbl	0x3(%rdi,%rcx), %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	WORD $0x014c; BYTE $0xc0 // addq	%r8, %rax
	LONG $0x04c18348 // addq	$0x4, %rcx
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JNE LBB0_14
LBB0_15:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	MOVQ AX, ret+16(FP)
	RET

