// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func hammingSve2(a unsafe.Pointer, b unsafe.Pointer, n int64) int64

//go:noescape
func jaccardSve2(a unsafe.Pointer, b unsafe.Pointer, n int64, result unsafe.Pointer)

//go:noescape
func popcountSve2(a unsafe.Pointer, n int64) int64

