// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

#include "textflag.h"

TEXT ·hammingAvx2(SB), NOSPLIT, $0-48
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX
	MOVQ lookup_ptr+24(FP), CX
	MOVQ low_mask_ptr+32(FP), R8

	LONG $0x20fa8348 // cmpq	$0x20, %rdx
	JGE LBB1_2
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0xc931 // xorl	%ecx, %ecx
	JMP LBB1_9
LBB1_2:
	LONG $0x016ffec5 // vmovdqu	(%rcx), %ymm0
	LONG $0x6f7ec1c4; BYTE $0x10 // vmovdqu	(%r8), %ymm2
	LONG $0xe0428d48 // leaq	-0x20(%rdx), %rax
	LONG $0x20f88348 // cmpq	$0x20, %rax
	JAE LBB1_4
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
	JMP LBB1_6
LBB1_4:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0x05e9c148 // shrq	$0x5, %rcx
	WORD $0xff48; BYTE $0xc1 // incq	%rcx
	LONG $0xfee18348 // andq	$-0x2, %rcx
	LONG $0xdbefe1c5 // vpxor	%xmm3, %xmm3, %xmm3
	WORD $0x3145; BYTE $0xc0 // xorl	%r8d, %r8d
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
LBB1_5:
	LONG $0x6f7ea1c4; WORD $0x0624 // vmovdqu	(%rsi,%r8), %ymm4
	LONG $0x6f7ea1c4; WORD $0x066c; BYTE $0x20 // vmovdqu	0x20(%rsi,%r8), %ymm5
	LONG $0xef5da1c4; WORD $0x0724 // vpxor	(%rdi,%r8), %ymm4, %ymm4
	LONG $0xf2dbddc5 // vpand	%ymm2, %ymm4, %ymm6
	LONG $0xd471ddc5; BYTE $0x04 // vpsrlw	$0x4, %ymm4, %ymm4
	LONG $0xe4dbedc5 // vpand	%ymm4, %ymm2, %ymm4
	LONG $0x007de2c4; BYTE $0xf6 // vpshufb	%ymm6, %ymm0, %ymm6
	LONG $0x007de2c4; BYTE $0xe4 // vpshufb	%ymm4, %ymm0, %ymm4
	LONG $0xe6fcddc5 // vpaddb	%ymm6, %ymm4, %ymm4
	LONG $0xe3f6ddc5 // vpsadbw	%ymm3, %ymm4, %ymm4
	LONG $0xc9d4ddc5 // vpaddq	%ymm1, %ymm4, %ymm1
	LONG $0xef55a1c4; WORD $0x0764; BYTE $0x20 // vpxor	0x20(%rdi,%r8), %ymm5, %ymm4
	LONG $0xeadbddc5 // vpand	%ymm2, %ymm4, %ymm5
	LONG $0xd471ddc5; BYTE $0x04 // vpsrlw	$0x4, %ymm4, %ymm4
	LONG $0xe4dbedc5 // vpand	%ymm4, %ymm2, %ymm4
	LONG $0x007de2c4; BYTE $0xed // vpshufb	%ymm5, %ymm0, %ymm5
	LONG $0x007de2c4; BYTE $0xe4 // vpshufb	%ymm4, %ymm0, %ymm4
	LONG $0xe5fcddc5 // vpaddb	%ymm5, %ymm4, %ymm4
	LONG $0xe3f6ddc5 // vpsadbw	%ymm3, %ymm4, %ymm4
	LONG $0xc9d4ddc5 // vpaddq	%ymm1, %ymm4, %ymm1
	LONG $0x40c08349 // addq	$0x40, %r8
	LONG $0xfec18348 // addq	$-0x2, %rcx
	JNE LBB1_5
LBB1_6:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0xe0e18348 // andq	$-0x20, %rcx
	WORD $0x20a8 // testb	$0x20, %al
	JNE LBB1_8
	LONG $0x6f7ea1c4; WORD $0x061c // vmovdqu	(%rsi,%r8), %ymm3
	LONG $0xef65a1c4; WORD $0x071c // vpxor	(%rdi,%r8), %ymm3, %ymm3
	LONG $0xe2dbe5c5 // vpand	%ymm2, %ymm3, %ymm4
	LONG $0xd371e5c5; BYTE $0x04 // vpsrlw	$0x4, %ymm3, %ymm3
	LONG $0xd3dbedc5 // vpand	%ymm3, %ymm2, %ymm2
	LONG $0x007de2c4; BYTE $0xdc // vpshufb	%ymm4, %ymm0, %ymm3
	LONG $0x007de2c4; BYTE $0xc2 // vpshufb	%ymm2, %ymm0, %ymm0
	LONG $0xc3fcfdc5 // vpaddb	%ymm3, %ymm0, %ymm0
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xc2f6fdc5 // vpsadbw	%ymm2, %ymm0, %ymm0
	LONG $0xc9d4fdc5 // vpaddq	%ymm1, %ymm0, %ymm1
LBB1_8:
	LONG $0x20c18348 // addq	$0x20, %rcx
LBB1_9:
	LONG $0xc170f9c5; BYTE $0xee // vpshufd	$0xee, %xmm1, %xmm0     # xmm0 = xmm1[2,3,2,3]
	LONG $0x397de3c4; WORD $0x01ca // vextracti128	$0x1, %ymm1, %xmm2
	LONG $0x00fde3c4; WORD $0xffd9 // vpermq	$0xff, %ymm1, %ymm3     # ymm3 = ymm1[3,3,3,3]
	LONG $0xc0d4f1c5 // vpaddq	%xmm0, %xmm1, %xmm0
	LONG $0xcbd4e9c5 // vpaddq	%xmm3, %xmm2, %xmm1
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	%xmm0, %rax
	WORD $0x3948; BYTE $0xca // cmpq	%rcx, %rdx
	JLE LBB1_15
	WORD $0x8941; BYTE $0xd0 // movl	%edx, %r8d
	WORD $0x2941; BYTE $0xc8 // subl	%ecx, %r8d
	LONG $0x01c0f641 // testb	$0x1, %r8b
	JNE LBB1_12
	WORD $0x8949; BYTE $0xc8 // movq	%rcx, %r8
	LONG $0xff4a8d4c // leaq	-0x1(%rdx), %r9
	WORD $0x394c; BYTE $0xc9 // cmpq	%r9, %rcx
	JNE LBB1_14
	JMP LBB1_15
LBB1_12:
	LONG $0x04b60f44; BYTE $0x0e // movzbl	(%rsi,%rcx), %r8d
	LONG $0x0f043244 // xorb	(%rdi,%rcx), %r8b
	LONG $0xc0b60f45 // movzbl	%r8b, %r8d
	LONG $0xb80f45f3; BYTE $0xc0 // popcntl	%r8d, %r8d
	WORD $0x014c; BYTE $0xc0 // addq	%r8, %rax
	LONG $0x01418d4c // leaq	0x1(%rcx), %r8
	LONG $0xff4a8d4c // leaq	-0x1(%rdx), %r9
	WORD $0x394c; BYTE $0xc9 // cmpq	%r9, %rcx
	JE LBB1_15
LBB1_14:
	LONG $0x0cb60f42; BYTE $0x06 // movzbl	(%rsi,%r8), %ecx
	LONG $0x4cb60f46; WORD $0x0106 // movzbl	0x1(%rsi,%r8), %r9d
	LONG $0x070c3242 // xorb	(%rdi,%r8), %cl
	WORD $0xb60f; BYTE $0xc9 // movzbl	%cl, %ecx
	LONG $0xc9b80ff3 // popcntl	%ecx, %ecx
	WORD $0x0148; BYTE $0xc1 // addq	%rax, %rcx
	LONG $0x074c3246; BYTE $0x01 // xorb	0x1(%rdi,%r8), %r9b
	LONG $0xc1b60f41 // movzbl	%r9b, %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	WORD $0x0148; BYTE $0xc8 // addq	%rcx, %rax
	LONG $0x02c08349 // addq	$0x2, %r8
	WORD $0x394c; BYTE $0xc2 // cmpq	%r8, %rdx
	JNE LBB1_14
LBB1_15:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	MOVQ AX, ret+40(FP)
	RET

TEXT ·popcountAvx2(SB), NOSPLIT, $0-40
	MOVQ a+0(FP), DI
	MOVQ n+8(FP), SI
	MOVQ lookup_ptr+16(FP), DX
	MOVQ low_mask_ptr+24(FP), CX

	LONG $0x20fe8348 // cmpq	$0x20, %rsi
	JGE LBB0_2
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0xc931 // xorl	%ecx, %ecx
	JMP LBB0_9
LBB0_2:
	LONG $0x026ffec5 // vmovdqu	(%rdx), %ymm0
	LONG $0x116ffec5 // vmovdqu	(%rcx), %ymm2
	LONG $0xe0468d48 // leaq	-0x20(%rsi), %rax
	LONG $0x20f88348 // cmpq	$0x20, %rax
	JAE LBB0_4
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
	WORD $0xd231 // xorl	%edx, %edx
	JMP LBB0_6
LBB0_4:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0x05e9c148 // shrq	$0x5, %rcx
	WORD $0xff48; BYTE $0xc1 // incq	%rcx
	LONG $0xfee18348 // andq	$-0x2, %rcx
	LONG $0xdbefe1c5 // vpxor	%xmm3, %xmm3, %xmm3
	WORD $0xd231 // xorl	%edx, %edx
	LONG $0xc9eff1c5 // vpxor	%xmm1, %xmm1, %xmm1
LBB0_5:
	LONG $0x246ffec5; BYTE $0x17 // vmovdqu	(%rdi,%rdx), %ymm4
	LONG $0x6c6ffec5; WORD $0x2017 // vmovdqu	0x20(%rdi,%rdx), %ymm5
	LONG $0xf2dbddc5 // vpand	%ymm2, %ymm4, %ymm6
	LONG $0xd471ddc5; BYTE $0x04 // vpsrlw	$0x4, %ymm4, %ymm4
	LONG $0xe4dbedc5 // vpand	%ymm4, %ymm2, %ymm4
	LONG $0x007de2c4; BYTE $0xf6 // vpshufb	%ymm6, %ymm0, %ymm6
	LONG $0x007de2c4; BYTE $0xe4 // vpshufb	%ymm4, %ymm0, %ymm4
	LONG $0xe6fcddc5 // vpaddb	%ymm6, %ymm4, %ymm4
	LONG $0xe3f6ddc5 // vpsadbw	%ymm3, %ymm4, %ymm4
	LONG $0xc9d4ddc5 // vpaddq	%ymm1, %ymm4, %ymm1
	LONG $0xe2dbd5c5 // vpand	%ymm2, %ymm5, %ymm4
	LONG $0xd571d5c5; BYTE $0x04 // vpsrlw	$0x4, %ymm5, %ymm5
	LONG $0xeddbedc5 // vpand	%ymm5, %ymm2, %ymm5
	LONG $0x007de2c4; BYTE $0xe4 // vpshufb	%ymm4, %ymm0, %ymm4
	LONG $0x007de2c4; BYTE $0xed // vpshufb	%ymm5, %ymm0, %ymm5
	LONG $0xe4fcd5c5 // vpaddb	%ymm4, %ymm5, %ymm4
	LONG $0xe3f6ddc5 // vpsadbw	%ymm3, %ymm4, %ymm4
	LONG $0xc9d4ddc5 // vpaddq	%ymm1, %ymm4, %ymm1
	LONG $0x40c28348 // addq	$0x40, %rdx
	LONG $0xfec18348 // addq	$-0x2, %rcx
	JNE LBB0_5
LBB0_6:
	WORD $0x8948; BYTE $0xc1 // movq	%rax, %rcx
	LONG $0xe0e18348 // andq	$-0x20, %rcx
	WORD $0x20a8 // testb	$0x20, %al
	JNE LBB0_8
	LONG $0x1c6ffec5; BYTE $0x17 // vmovdqu	(%rdi,%rdx), %ymm3
	LONG $0xe2dbe5c5 // vpand	%ymm2, %ymm3, %ymm4
	LONG $0xd371e5c5; BYTE $0x04 // vpsrlw	$0x4, %ymm3, %ymm3
	LONG $0xd3dbedc5 // vpand	%ymm3, %ymm2, %ymm2
	LONG $0x007de2c4; BYTE $0xdc // vpshufb	%ymm4, %ymm0, %ymm3
	LONG $0x007de2c4; BYTE $0xc2 // vpshufb	%ymm2, %ymm0, %ymm0
	LONG $0xc3fcfdc5 // vpaddb	%ymm3, %ymm0, %ymm0
	LONG $0xd2efe9c5 // vpxor	%xmm2, %xmm2, %xmm2
	LONG $0xc2f6fdc5 // vpsadbw	%ymm2, %ymm0, %ymm0
	LONG $0xc9d4fdc5 // vpaddq	%ymm1, %ymm0, %ymm1
LBB0_8:
	LONG $0x20c18348 // addq	$0x20, %rcx
LBB0_9:
	LONG $0xc170f9c5; BYTE $0xee // vpshufd	$0xee, %xmm1, %xmm0     # xmm0 = xmm1[2,3,2,3]
	LONG $0x397de3c4; WORD $0x01ca // vextracti128	$0x1, %ymm1, %xmm2
	LONG $0x00fde3c4; WORD $0xffd9 // vpermq	$0xff, %ymm1, %ymm3     # ymm3 = ymm1[3,3,3,3]
	LONG $0xc0d4f1c5 // vpaddq	%xmm0, %xmm1, %xmm0
	LONG $0xcbd4e9c5 // vpaddq	%xmm3, %xmm2, %xmm1
	LONG $0xc1d4f9c5 // vpaddq	%xmm1, %xmm0, %xmm0
	LONG $0x7ef9e1c4; BYTE $0xc0 // vmovq	%xmm0, %rax
	WORD $0x8948; BYTE $0xca // movq	%rcx, %rdx
	WORD $0x2948; BYTE $0xf2 // subq	%rsi, %rdx
	JGE LBB0_14
	WORD $0x8941; BYTE $0xf0 // movl	%esi, %r8d
	WORD $0x2941; BYTE $0xc8 // subl	%ecx, %r8d
	LONG $0x03e08341 // andl	$0x3, %r8d
	JE LBB0_12
LBB0_11:
	LONG $0x0cb60f44; BYTE $0x0f // movzbl	(%rdi,%rcx), %r9d
	LONG $0xb80f45f3; BYTE $0xc9 // popcntl	%r9d, %r9d
	WORD $0x014c; BYTE $0xc8 // addq	%r9, %rax
	WORD $0xff48; BYTE $0xc1 // incq	%rcx
	WORD $0xff49; BYTE $0xc8 // decq	%r8
	JNE LBB0_11
LBB0_12:
	LONG $0xfcfa8348 // cmpq	$-0x4, %rdx
	JHI LBB0_14
LBB0_13:
	LONG $0x0f14b60f // movzbl	(%rdi,%rcx), %edx
	LONG $0xd2b80ff3 // popcntl	%edx, %edx
	WORD $0x0148; BYTE $0xc2 // addq	%rax, %rdx
	LONG $0x0f44b60f; BYTE $0x01 // movzbl	0x1(%rdi,%rcx), %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	LONG $0x44b60f44; WORD $0x020f // movzbl	0x2(%rdi,%rcx), %r8d
	LONG $0xb80f45f3; BYTE $0xc0 // popcntl	%r8d, %r8d
	WORD $0x0149; BYTE $0xc0 // addq	%rax, %r8
	WORD $0x0149; BYTE $0xd0 // addq	%rdx, %r8
	LONG $0x0f44b60f; BYTE $0x03 // movzbl	0x3(%rdi,%rcx), %eax
	LONG $0xc0b80ff3 // popcntl	%eax, %eax
	WORD $0x014c; BYTE $0xc0 // addq	%r8, %rax
	LONG $0x04c18348 // addq	$0x4, %rcx
	WORD $0x3948; BYTE $0xce // cmpq	%rcx, %rsi
	JNE LBB0_13
LBB0_14:
	WORD $0xf8c5; BYTE $0x77 // vzeroupper
	MOVQ AX, ret+32(FP)
	RET

