// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func hammingAvx(a unsafe.Pointer, b unsafe.Pointer, n int64, lookup_ptr unsafe.Pointer, low_mask_ptr unsafe.Pointer) int64
