// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && amd64

package simd

import "unsafe"

//go:noescape
func buildDistanceTableInt8Avx2(query unsafe.Pointer, codebook unsafe.Pointer, subdim int64, scale unsafe.Pointer, offset unsafe.Pointer, out unsafe.Pointer)

//go:noescape
func findNearestCentroidInt8Avx2(query unsafe.Pointer, codebook unsafe.Pointer, subdim int64, scale unsafe.Pointer, offset unsafe.Pointer, outIndex unsafe.Pointer)

//go:noescape
func squaredL2Int8DequantizedAvx2(query unsafe.Pointer, code unsafe.Pointer, subdim int64, scale unsafe.Pointer, offset unsafe.Pointer, out unsafe.Pointer)

