// Code generated by internal/simd/cmd/generator. DO NOT EDIT.

//go:build !noasm && arm64

package simd

import "unsafe"

//go:noescape
func sq8uL2BatchPerDimensionSve2(query unsafe.Pointer, codes unsafe.Pointer, mins unsafe.Pointer, invScales unsafe.Pointer, dim int64, n int64, out unsafe.Pointer)
